/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.sun.glass.events.KeyEvent;
import controller.ConexionDB;
import java.awt.HeadlessException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ace
 */
public class Login_frm extends javax.swing.JFrame {

    /**
     * Creates new form puesto
     */
    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    String sqlSelect;
    String sqlSelect_Valor;
    String sqlInsert;
    String sqlDelete;

    public Login_frm() throws IOException {
        initComponents();
        

        //inicialización de las variables de la coneccion a la base de datos
        con = ConexionDB.conexionDB();
        //llama al procedimiento de obtener la información.
        Get_Data();
        //centra la ventana para que se inicie en el centro del escritorio
        this.setLocationRelativeTo(null);
        initState();
        sqlSelect = "SELECT `idusuario`, `usuario`, `password`, `colaborador_empleado_id` FROM `usuario` ORDER BY `desc_persona`";
        sqlSelect_Valor = "SELECT `idusuario`, `usuario`, `password`, `colaborador_empleado_id` FROM `usuario` WHERE `usuario` = '";

        ////INSERT INTO `Horario_frm`(`descripcion_horario`) VALUES (" ")
        sqlInsert = "INSERT INTO `usuario`(`usuario`, `password`, `colaborador_empleado_id`) VALUES ('";
        sqlDelete = "DELETE FROM `usuario` WHERE `idusuario` = ";
    }

    private void initState() {
        txt_User.setEnabled(false);
        lbl_idUsuario.setText("");
        txt_User.setText("");
        
        Get_Data();

    }

    private void Get_Data() {
        //Select sobre el estatus_empleado y se le asigna el valor a la columna de la tabla del formulario.
        String sql = "SELECT `desc_persona` as 'Descripción de Persona' FROM `tipo_persona` ORDER BY `desc_persona`";

        try {
            pst = con.prepareStatement(sql);

            rs = pst.executeQuery();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_User = new javax.swing.JTextField();
        txt_Pass = new javax.swing.JPasswordField();
        fondo1 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        lbl_idUsuario = new javax.swing.JLabel();
        lbl_colaborador_empleado_id = new javax.swing.JLabel();
        lbl_Entrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login");
        setUndecorated(true);
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_User.setBackground(new java.awt.Color(255, 255, 255));
        txt_User.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        txt_User.setForeground(new java.awt.Color(0, 0, 0));
        txt_User.setBorder(null);
        getContentPane().add(txt_User, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 220, 40));

        txt_Pass.setBackground(new java.awt.Color(255, 255, 255));
        txt_Pass.setForeground(new java.awt.Color(0, 0, 0));
        txt_Pass.setBorder(null);
        getContentPane().add(txt_Pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 220, 40));

        fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/CRUD/CustomLoginForms_01.jpg"))); // NOI18N
        fondo1.setOpaque(true);
        fondo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fondo1MouseClicked(evt);
            }
        });
        getContentPane().add(fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 260));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/FondoAzul.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 260));

        lbl_idUsuario.setText("jLabel1");
        getContentPane().add(lbl_idUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        lbl_colaborador_empleado_id.setText("jLabel1");
        getContentPane().add(lbl_colaborador_empleado_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        lbl_Entrar.setText("jLabel1");
        getContentPane().add(lbl_Entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 60, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fondo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fondo1MouseClicked
        // TODO add your handling code here:
        Principal principal = new Principal();
        this.hide();
        principal.setVisible(true);
    }//GEN-LAST:event_fondo1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new Login_frm().setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(Login_frm.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel fondo1;
    private javax.swing.JLabel lbl_Entrar;
    private javax.swing.JLabel lbl_colaborador_empleado_id;
    private javax.swing.JLabel lbl_idUsuario;
    private javax.swing.JPasswordField txt_Pass;
    private javax.swing.JTextField txt_User;
    // End of variables declaration//GEN-END:variables
}
