/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model;

import static java.lang.Integer.parseInt;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Cesar Gonzalez Salas, Eisner Lopez Acevedo
 */
public class Facturar_Cabina extends javax.swing.JFrame {

    /**
     * Creates new form Facturar_Cabina
     */
    public Facturar_Cabina() {
        initComponents();

        setLocationRelativeTo(null);

        try {
            // crea mysql database connection
            String myDriver = "org.gjt.mm.mysql.Driver";
            String myUrl = "jdbc:mysql://localhost:3306/PCT2?zeroDateTimeBehavior=convertToNull";
            Class.forName(myDriver);
            Connection conn = DriverManager.getConnection(myUrl, "root", "surfing");

            // SQL SELECT query. 
            String query = "SELECT * FROM ocupacion";

            // crea el java statement
            Statement st = conn.createStatement();

            // ejecuta el query y obtiene el java resultset
            ResultSet rs = st.executeQuery(query);

            // interactua con el java resultset
            while (rs.next()) {
                int Ocupacion_id = rs.getInt("Ocupacion_id");

                // Si ocupacion_id = 1 bloquea el boton al inicio para que no se vuelva  a facturar
                if (Ocupacion_id == 1) {
                    btnCabin1.setEnabled(false);
                }

            }
            st.close();
        } catch (Exception e) {
            System.err.println("Got an exception! ");
            System.err.println(e.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCabin1 = new javax.swing.JButton();
        btnCabin2 = new javax.swing.JButton();
        btnCabin4 = new javax.swing.JButton();
        btnCabin5 = new javax.swing.JButton();
        btnCabin3 = new javax.swing.JButton();
        btnCabin6 = new javax.swing.JButton();
        btnCabin7 = new javax.swing.JButton();
        btnCabin8 = new javax.swing.JButton();
        btnCabin9 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        mnuDesbloquea = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFocusTraversalPolicyProvider(true);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCabin1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnCabin1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/casa.png"))); // NOI18N
        btnCabin1.setText("Cabina 1");
        btnCabin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCabin1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnCabin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 21, -1, 87));

        btnCabin2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnCabin2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/casa.png"))); // NOI18N
        btnCabin2.setText("Cabina 1");
        btnCabin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCabin2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnCabin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 21, -1, 87));

        btnCabin4.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnCabin4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/casa.png"))); // NOI18N
        btnCabin4.setText("Cabina 1");
        btnCabin4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCabin4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnCabin4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 87));

        btnCabin5.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnCabin5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/casa.png"))); // NOI18N
        btnCabin5.setText("Cabina 1");
        btnCabin5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCabin5ActionPerformed(evt);
            }
        });
        getContentPane().add(btnCabin5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, 87));

        btnCabin3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnCabin3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/casa.png"))); // NOI18N
        btnCabin3.setText("Cabina 1");
        btnCabin3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCabin3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnCabin3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, 87));

        btnCabin6.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnCabin6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/casa.png"))); // NOI18N
        btnCabin6.setText("Cabina 1");
        btnCabin6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCabin6ActionPerformed(evt);
            }
        });
        getContentPane().add(btnCabin6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, -1, 87));

        btnCabin7.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnCabin7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/casa.png"))); // NOI18N
        btnCabin7.setText("Cabina 1");
        btnCabin7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCabin7ActionPerformed(evt);
            }
        });
        getContentPane().add(btnCabin7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, 87));

        btnCabin8.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnCabin8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/casa.png"))); // NOI18N
        btnCabin8.setText("Cabina 1");
        btnCabin8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCabin8ActionPerformed(evt);
            }
        });
        getContentPane().add(btnCabin8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, 87));

        btnCabin9.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        btnCabin9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/casa.png"))); // NOI18N
        btnCabin9.setText("Cabina 1");
        btnCabin9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCabin9ActionPerformed(evt);
            }
        });
        getContentPane().add(btnCabin9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, -1, 87));

        jMenu3.setText("Menu");

        mnuDesbloquea.setIcon(new javax.swing.ImageIcon("/home/ace/project/Proyecto_Cabinas_Eltropico/src/Icons/unlocked.png")); // NOI18N
        mnuDesbloquea.setText("Desbloquear Cabina");
        mnuDesbloquea.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                mnuDesbloqueaMenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        jMenu3.add(mnuDesbloquea);
        jMenu3.add(jSeparator1);

        mnuSalir.setIcon(new javax.swing.ImageIcon("/home/ace/project/Proyecto_Cabinas_Eltropico/src/Icons/exit-sign.png")); // NOI18N
        mnuSalir.setText("Salir");
        mnuSalir.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                mnuSalirMenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        mnuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuSalirMouseClicked(evt);
            }
        });
        jMenu3.add(mnuSalir);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuSalirMenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_mnuSalirMenuKeyPressed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_mnuSalirMenuKeyPressed

    private void mnuDesbloqueaMenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_mnuDesbloqueaMenuKeyPressed
        // TODO add your handling code here:
        // TODO add your handling code here:

        JFrame frame = new JFrame("InputDialog");
        String NumCabina = JOptionPane.showInputDialog(
                frame,
                "Digite El Número De Cabina a Desbloquear!",
                "Numero De Cabina",
                JOptionPane.WARNING_MESSAGE
        );

        int NumCabina1 = parseInt(NumCabina);

        switch (NumCabina1) {

            case 1:

                try {

                    // crea mysql database connection
                    String myDriver = "org.gjt.mm.mysql.Driver";
                    String myUrl = "jdbc:mysql://localhost/cabinas_el_tropico";
                    Class.forName(myDriver);
                    Connection conn = DriverManager.getConnection(myUrl, "root", "");

                    //Crea el update
                    String sql = "UPDATE Ocupacion SET Ocupacion_id = ?, Cabina_id = ? WHERE Ocupacion_id = '1'";

                    // crea mysql preparedstatement
                    PreparedStatement statement = conn.prepareStatement(sql);
                    statement.setInt(1, 0);
                    statement.setInt(2, 0);

                    // Ejecuta el Update y bloquea el boton 
                    int rowsUpdated = statement.executeUpdate();
                    if (rowsUpdated > 0) {
                        btnCabin1.setEnabled(true);
                        System.out.println(" Fuck Yeah!!!!");

                    }

                } catch (ClassNotFoundException | SQLException e) {

                    System.err.println("Got an exception!");

                }
                break;
        }
    }//GEN-LAST:event_mnuDesbloqueaMenuKeyPressed

    private void mnuSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuSalirMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_mnuSalirMouseClicked

    private void btnCabin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCabin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCabin1ActionPerformed

    private void btnCabin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCabin2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCabin2ActionPerformed

    private void btnCabin4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCabin4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCabin4ActionPerformed

    private void btnCabin5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCabin5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCabin5ActionPerformed

    private void btnCabin3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCabin3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCabin3ActionPerformed

    private void btnCabin6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCabin6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCabin6ActionPerformed

    private void btnCabin7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCabin7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCabin7ActionPerformed

    private void btnCabin8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCabin8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCabin8ActionPerformed

    private void btnCabin9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCabin9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCabin9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Facturar_Cabina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Facturar_Cabina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Facturar_Cabina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Facturar_Cabina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Facturar_Cabina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCabin1;
    private javax.swing.JButton btnCabin2;
    private javax.swing.JButton btnCabin3;
    private javax.swing.JButton btnCabin4;
    private javax.swing.JButton btnCabin5;
    private javax.swing.JButton btnCabin6;
    private javax.swing.JButton btnCabin7;
    private javax.swing.JButton btnCabin8;
    private javax.swing.JButton btnCabin9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu mnuDesbloquea;
    private javax.swing.JMenu mnuSalir;
    // End of variables declaration//GEN-END:variables
}
