package model;

import java.util.Calendar;
import java.util.GregorianCalendar;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Cesar Gonzalez Salas, Eisner Lopez Acevedo
 */
public class Pantalla_principal extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla_principal
     */
    public Pantalla_principal() {
        initComponents();
        setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);

        // coloca la hora en el FRM
        Calendar calendario = Calendar.getInstance();
        calendario = new GregorianCalendar();
        int hora, minutos, segundos;
        hora = calendario.get(Calendar.HOUR_OF_DAY);
        minutos = calendario.get(Calendar.MINUTE);
        segundos = calendario.get(Calendar.SECOND);
        String Reloj = (hora + ":" + minutos + ":" + segundos);
        jTxtFHora.setText(Reloj);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jBtn_FacturarCabinas = new javax.swing.JButton();
        jTxtFHora = new javax.swing.JTextField();
        fondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuSalir = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        mnUsuario = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtn_FacturarCabinas.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jBtn_FacturarCabinas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Home-50.png"))); // NOI18N
        jBtn_FacturarCabinas.setText("Facturar Cabinas");
        jBtn_FacturarCabinas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtn_FacturarCabinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_FacturarCabinasActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn_FacturarCabinas, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 1142, 181, 72));

        jTxtFHora.setFont(new java.awt.Font("FreeSans", 1, 18)); // NOI18N
        jTxtFHora.setForeground(new java.awt.Color(255, 255, 255));
        jTxtFHora.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jTxtFHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(1760, 0, 160, 60));

        fondo.setIcon(new javax.swing.ImageIcon("/home/ace/project/Proyecto_Cabinas_Eltropico/src/Icons/surface.jpg")); // NOI18N
        fondo.setAutoscrolls(true);
        fondo.setMaximumSize(new java.awt.Dimension(800, 600));
        fondo.setMinimumSize(new java.awt.Dimension(800, 600));
        fondo.setName(""); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenu1.setText("File");

        mnuSalir.setIcon(new javax.swing.ImageIcon("/home/ace/project/Proyecto_Cabinas_Eltropico/src/Icons/exit-sign.png")); // NOI18N
        mnuSalir.setText("Salir");
        mnuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuSalirMouseClicked(evt);
            }
        });
        jMenu1.add(mnuSalir);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Menu Cabina");

        jMenu3.setIcon(new javax.swing.ImageIcon("/home/ace/project/Proyecto_Cabinas_Eltropico/src/Icons/receipt.png")); // NOI18N
        jMenu3.setText("Facturar Cabina");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenu4.add(jMenu3);

        jMenuBar1.add(jMenu4);

        jMenu2.setText("Lista Usuarios");

        mnUsuario.setText("Listar Usarios");
        mnUsuario.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                mnUsuarioMenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        mnUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnUsuarioMouseClicked(evt);
            }
        });
        jMenu2.add(mnUsuario);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Acerca");

        jMenu6.setText("De...");
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });
        jMenu5.add(jMenu6);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn_FacturarCabinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_FacturarCabinasActionPerformed
        // TODO add your handling code here:

        Facturar_Cabina Fact_Cab = new Facturar_Cabina();
        Fact_Cab.setVisible(true);
    }//GEN-LAST:event_jBtn_FacturarCabinasActionPerformed

    private void mnuSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuSalirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnuSalirMouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
        Facturar_Cabina Fact_Cab = new Facturar_Cabina();
        Fact_Cab.setVisible(true);
    }//GEN-LAST:event_jMenu3MouseClicked

    private void mnUsuarioMenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_mnUsuarioMenuKeyPressed
        // TODO add your handling code here:
        DetalleLogin detalleLogin = new DetalleLogin();
        detalleLogin.setVisible(true);
    }//GEN-LAST:event_mnUsuarioMenuKeyPressed

    private void mnUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnUsuarioMouseClicked
        // TODO add your handling code here:
        DetalleLogin detalleLogin = new DetalleLogin();
        detalleLogin.setVisible(true);
    }//GEN-LAST:event_mnUsuarioMouseClicked

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked
        // TODO add your handling code here:
        About about = new About();
        about.setVisible(true);
    }//GEN-LAST:event_jMenu6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jBtn_FacturarCabinas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField jTxtFHora;
    private javax.swing.JMenu mnUsuario;
    private javax.swing.JMenu mnuSalir;
    // End of variables declaration//GEN-END:variables
}
