-- MySQL Script generated by MySQL Workbench
-- lun 13 feb 2017 13:50:01 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pct3
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pct3` ;

-- -----------------------------------------------------
-- Schema pct3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pct3` DEFAULT CHARACTER SET utf8 ;
USE `pct3` ;

-- -----------------------------------------------------
-- Table `pct3`.`precio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pct3`.`precio` ;

CREATE TABLE IF NOT EXISTS `pct3`.`precio` (
  `precio_id` TINYINT(4) NOT NULL AUTO_INCREMENT,
  `descripcion_precio` VARCHAR(30) NOT NULL,
  `monto_precio` FLOAT NOT NULL,
  PRIMARY KEY (`precio_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pct3`.`cabina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pct3`.`cabina` ;

CREATE TABLE IF NOT EXISTS `pct3`.`cabina` (
  `cabina_id` SMALLINT(6) NOT NULL AUTO_INCREMENT,
  `descripcion_cabina` VARCHAR(30) NOT NULL,
  `estado_cabina` VARCHAR(45) NOT NULL,
  `precio_precio_id` TINYINT(4) NOT NULL,
  PRIMARY KEY (`cabina_id`),
  CONSTRAINT `fk_cabina_precio1`
    FOREIGN KEY (`precio_precio_id`)
    REFERENCES `pct3`.`precio` (`precio_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Almacena el nombre de la cabina y actualizará el estado de ocupado a vacio.';

CREATE UNIQUE INDEX `descripcion_cabina_UNIQUE` ON `pct3`.`cabina` (`descripcion_cabina` ASC);

CREATE INDEX `fk_cabina_precio1_idx` ON `pct3`.`cabina` (`precio_precio_id` ASC);


-- -----------------------------------------------------
-- Table `pct3`.`tipo_persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pct3`.`tipo_persona` ;

CREATE TABLE IF NOT EXISTS `pct3`.`tipo_persona` (
  `idtipo_persona` INT NOT NULL AUTO_INCREMENT,
  `desc_persona` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtipo_persona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pct3`.`persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pct3`.`persona` ;

CREATE TABLE IF NOT EXISTS `pct3`.`persona` (
  `idpersona` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `cedula` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `tipo_persona_idtipo_persona` INT NOT NULL,
  PRIMARY KEY (`idpersona`),
  CONSTRAINT `fk_persona_tipo_persona1`
    FOREIGN KEY (`tipo_persona_idtipo_persona`)
    REFERENCES `pct3`.`tipo_persona` (`idtipo_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_persona_tipo_persona1_idx` ON `pct3`.`persona` (`tipo_persona_idtipo_persona` ASC);


-- -----------------------------------------------------
-- Table `pct3`.`empresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pct3`.`empresa` ;

CREATE TABLE IF NOT EXISTS `pct3`.`empresa` (
  `empresa_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `nombre_empresa` VARCHAR(45) NOT NULL,
  `persona_idpersona` INT NOT NULL,
  PRIMARY KEY (`empresa_id`),
  CONSTRAINT `fk_empresa_persona1`
    FOREIGN KEY (`persona_idpersona`)
    REFERENCES `pct3`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_empresa_persona1_idx` ON `pct3`.`empresa` (`persona_idpersona` ASC);


-- -----------------------------------------------------
-- Table `pct3`.`horario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pct3`.`horario` ;

CREATE TABLE IF NOT EXISTS `pct3`.`horario` (
  `horario_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `descripcion_horario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`horario_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pct3`.`puesto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pct3`.`puesto` ;

CREATE TABLE IF NOT EXISTS `pct3`.`puesto` (
  `puesto_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `descripcion_puesto` VARCHAR(30) NOT NULL,
  `pago_hora_sencilla` FLOAT NOT NULL,
  `pago_hora_extra` FLOAT NOT NULL,
  PRIMARY KEY (`puesto_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pct3`.`colaborador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pct3`.`colaborador` ;

CREATE TABLE IF NOT EXISTS `pct3`.`colaborador` (
  `empleado_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `fecha_contrato` DATE NOT NULL,
  `fecha_despido` DATE NULL,
  `observaciones` VARCHAR(45) NULL,
  `persona_idpersona` INT NOT NULL,
  `horario_horario_id` BIGINT(20) NOT NULL,
  `puesto_puesto_id` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`empleado_id`),
  CONSTRAINT `fk_colaborador_persona`
    FOREIGN KEY (`persona_idpersona`)
    REFERENCES `pct3`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_colaborador_horario1`
    FOREIGN KEY (`horario_horario_id`)
    REFERENCES `pct3`.`horario` (`horario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_colaborador_puesto1`
    FOREIGN KEY (`puesto_puesto_id`)
    REFERENCES `pct3`.`puesto` (`puesto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_colaborador_persona_idx` ON `pct3`.`colaborador` (`persona_idpersona` ASC);

CREATE INDEX `fk_colaborador_horario1_idx` ON `pct3`.`colaborador` (`horario_horario_id` ASC);

CREATE INDEX `fk_colaborador_puesto1_idx` ON `pct3`.`colaborador` (`puesto_puesto_id` ASC);


-- -----------------------------------------------------
-- Table `pct3`.`datos_empresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pct3`.`datos_empresa` ;

CREATE TABLE IF NOT EXISTS `pct3`.`datos_empresa` (
  `iddatos_empresa` INT NOT NULL AUTO_INCREMENT,
  `empresa_nombre` VARCHAR(45) NOT NULL,
  `empresa_propietario` VARCHAR(45) NOT NULL,
  `empresa_sa` VARCHAR(45) NOT NULL,
  `empresa_cedula_juridica` VARCHAR(45) NOT NULL,
  `empresa_telefono1` VARCHAR(45) NOT NULL,
  `empresa_telefono2` VARCHAR(45) NOT NULL,
  `empresa_direccion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iddatos_empresa`))
ENGINE = InnoDB
COMMENT = 'Guarda la información que se muestra en la factura. Como son el dueño, nombre de la empresa, telefono. direccion';


-- -----------------------------------------------------
-- Table `pct3`.`factura_cabina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pct3`.`factura_cabina` ;

CREATE TABLE IF NOT EXISTS `pct3`.`factura_cabina` (
  `factura_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `cant_dia` TINYINT(4) NOT NULL,
  `fecha` DATE NOT NULL,
  `descuento_factura` FLOAT NOT NULL,
  `impuesto_cabina` FLOAT NOT NULL,
  `precio_total_cabina` BIGINT(20) NOT NULL,
  `cabina_cabina_id` SMALLINT(6) NOT NULL,
  `persona_idpersona` INT NOT NULL,
  `colaborador_empleado_id` BIGINT(20) NOT NULL,
  `datos_empresa_iddatos_empresa` INT NOT NULL,
  `persona_idpersona1` INT NOT NULL,
  PRIMARY KEY (`factura_id`),
  CONSTRAINT `fk_factura_cabina_cabina1`
    FOREIGN KEY (`cabina_cabina_id`)
    REFERENCES `pct3`.`cabina` (`cabina_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factura_cabina_persona1`
    FOREIGN KEY (`persona_idpersona`)
    REFERENCES `pct3`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factura_cabina_colaborador1`
    FOREIGN KEY (`colaborador_empleado_id`)
    REFERENCES `pct3`.`colaborador` (`empleado_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factura_cabina_datos_empresa1`
    FOREIGN KEY (`datos_empresa_iddatos_empresa`)
    REFERENCES `pct3`.`datos_empresa` (`iddatos_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factura_cabina_persona2`
    FOREIGN KEY (`persona_idpersona1`)
    REFERENCES `pct3`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_factura_cabina_cabina1_idx` ON `pct3`.`factura_cabina` (`cabina_cabina_id` ASC);

CREATE INDEX `fk_factura_cabina_persona1_idx` ON `pct3`.`factura_cabina` (`persona_idpersona` ASC);

CREATE INDEX `fk_factura_cabina_colaborador1_idx` ON `pct3`.`factura_cabina` (`colaborador_empleado_id` ASC);

CREATE INDEX `fk_factura_cabina_datos_empresa1_idx` ON `pct3`.`factura_cabina` (`datos_empresa_iddatos_empresa` ASC);

CREATE INDEX `fk_factura_cabina_persona2_idx` ON `pct3`.`factura_cabina` (`persona_idpersona1` ASC);


-- -----------------------------------------------------
-- Table `pct3`.`gasto_operativo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pct3`.`gasto_operativo` ;

CREATE TABLE IF NOT EXISTS `pct3`.`gasto_operativo` (
  `gasto_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `descripcion_gasto` VARCHAR(50) NOT NULL,
  `monto_gasto` MEDIUMINT(9) NOT NULL,
  `fecha_gasto` DATE NOT NULL,
  `factura_gasto` VARCHAR(45) NOT NULL,
  `colaborador_empleado_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`gasto_id`),
  CONSTRAINT `fk_gasto_operativo_colaborador1`
    FOREIGN KEY (`colaborador_empleado_id`)
    REFERENCES `pct3`.`colaborador` (`empleado_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_gasto_operativo_colaborador1_idx` ON `pct3`.`gasto_operativo` (`colaborador_empleado_id` ASC);


-- -----------------------------------------------------
-- Table `pct3`.`proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pct3`.`proveedor` ;

CREATE TABLE IF NOT EXISTS `pct3`.`proveedor` (
  `idproveedor` INT NOT NULL,
  `desc_proveedor` VARCHAR(45) NULL,
  `persona_idpersona` INT NOT NULL,
  PRIMARY KEY (`idproveedor`),
  CONSTRAINT `fk_proveedor_persona1`
    FOREIGN KEY (`persona_idpersona`)
    REFERENCES `pct3`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_proveedor_persona1_idx` ON `pct3`.`proveedor` (`persona_idpersona` ASC);


-- -----------------------------------------------------
-- Table `pct3`.`productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pct3`.`productos` ;

CREATE TABLE IF NOT EXISTS `pct3`.`productos` (
  `idproductos` INT NOT NULL,
  `monto_productos` VARCHAR(45) NULL,
  `desc_productos` VARCHAR(45) NULL,
  `fecha` DATE NULL,
  `proveedor_idproveedor` INT NOT NULL,
  PRIMARY KEY (`idproductos`),
  CONSTRAINT `fk_productos_proveedor1`
    FOREIGN KEY (`proveedor_idproveedor`)
    REFERENCES `pct3`.`proveedor` (`idproveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_productos_proveedor1_idx` ON `pct3`.`productos` (`proveedor_idproveedor` ASC);


-- -----------------------------------------------------
-- Table `pct3`.`inventario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pct3`.`inventario` ;

CREATE TABLE IF NOT EXISTS `pct3`.`inventario` (
  `inventario_id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_producto` VARCHAR(30) NOT NULL,
  `cant_producto` INT(11) NOT NULL,
  `fecha_compra_producto` DATE NOT NULL,
  `precio_inventario` FLOAT NOT NULL,
  `proveedor_proveedor_id` BIGINT(20) UNSIGNED NOT NULL,
  `productos_idproductos` INT NOT NULL,
  PRIMARY KEY (`inventario_id`),
  CONSTRAINT `fk_inventario_productos1`
    FOREIGN KEY (`productos_idproductos`)
    REFERENCES `pct3`.`productos` (`idproductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_inventario_productos1_idx` ON `pct3`.`inventario` (`productos_idproductos` ASC);


-- -----------------------------------------------------
-- Table `pct3`.`planilla`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pct3`.`planilla` ;

CREATE TABLE IF NOT EXISTS `pct3`.`planilla` (
  `planilla_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `descripcion_planilla` VARCHAR(30) NOT NULL,
  `fecha_planilla` DATE NOT NULL,
  `total_hora_sencilla` FLOAT NOT NULL,
  `total_hora_extra` FLOAT NOT NULL,
  `total_deduc_ccss` FLOAT NOT NULL,
  `deducciones` FLOAT NOT NULL,
  `monto_pago_planilla` FLOAT NOT NULL,
  `colaborador_empleado_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`planilla_id`),
  CONSTRAINT `fk_planilla_colaborador1`
    FOREIGN KEY (`colaborador_empleado_id`)
    REFERENCES `pct3`.`colaborador` (`empleado_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_planilla_colaborador1_idx` ON `pct3`.`planilla` (`colaborador_empleado_id` ASC);


-- -----------------------------------------------------
-- Table `pct3`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pct3`.`usuario` ;

CREATE TABLE IF NOT EXISTS `pct3`.`usuario` (
  `idusuario` INT NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `colaborador_empleado_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`idusuario`),
  CONSTRAINT `fk_usuario_colaborador1`
    FOREIGN KEY (`colaborador_empleado_id`)
    REFERENCES `pct3`.`colaborador` (`empleado_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_usuario_colaborador1_idx` ON `pct3`.`usuario` (`colaborador_empleado_id` ASC);


-- -----------------------------------------------------
-- Table `pct3`.`marcas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pct3`.`marcas` ;

CREATE TABLE IF NOT EXISTS `pct3`.`marcas` (
  `idmarcas` INT NOT NULL AUTO_INCREMENT,
  `hora_entrada` TIME NOT NULL,
  `hora_salild` TIME NOT NULL,
  `colaborador_empleado_id` BIGINT(20) NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`idmarcas`),
  CONSTRAINT `fk_marcas_colaborador1`
    FOREIGN KEY (`colaborador_empleado_id`)
    REFERENCES `pct3`.`colaborador` (`empleado_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_marcas_colaborador1_idx` ON `pct3`.`marcas` (`colaborador_empleado_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `pct3`.`precio`
-- -----------------------------------------------------
START TRANSACTION;
USE `pct3`;
INSERT INTO `pct3`.`precio` (`precio_id`, `descripcion_precio`, `monto_precio`) VALUES (DEFAULT, 'Sencilla', 10000);
INSERT INTO `pct3`.`precio` (`precio_id`, `descripcion_precio`, `monto_precio`) VALUES (DEFAULT, 'Doble', 15000);

COMMIT;


-- -----------------------------------------------------
-- Data for table `pct3`.`cabina`
-- -----------------------------------------------------
START TRANSACTION;
USE `pct3`;
INSERT INTO `pct3`.`cabina` (`cabina_id`, `descripcion_cabina`, `estado_cabina`, `precio_precio_id`) VALUES (DEFAULT, 'Uno', DEFAULT, DEFAULT);
INSERT INTO `pct3`.`cabina` (`cabina_id`, `descripcion_cabina`, `estado_cabina`, `precio_precio_id`) VALUES (DEFAULT, 'Dos', DEFAULT, DEFAULT);
INSERT INTO `pct3`.`cabina` (`cabina_id`, `descripcion_cabina`, `estado_cabina`, `precio_precio_id`) VALUES (DEFAULT, 'Tres', DEFAULT, DEFAULT);
INSERT INTO `pct3`.`cabina` (`cabina_id`, `descripcion_cabina`, `estado_cabina`, `precio_precio_id`) VALUES (DEFAULT, 'Cuatro', DEFAULT, DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `pct3`.`tipo_persona`
-- -----------------------------------------------------
START TRANSACTION;
USE `pct3`;
INSERT INTO `pct3`.`tipo_persona` (`idtipo_persona`, `desc_persona`) VALUES (1, 'Cliente');
INSERT INTO `pct3`.`tipo_persona` (`idtipo_persona`, `desc_persona`) VALUES (2, 'Proveedor');
INSERT INTO `pct3`.`tipo_persona` (`idtipo_persona`, `desc_persona`) VALUES (3, 'Colaborador');

COMMIT;


-- -----------------------------------------------------
-- Data for table `pct3`.`persona`
-- -----------------------------------------------------
START TRANSACTION;
USE `pct3`;
INSERT INTO `pct3`.`persona` (`idpersona`, `nombre`, `cedula`, `telefono`, `direccion`, `tipo_persona_idtipo_persona`) VALUES (DEFAULT, 'Eisner', '800850956', '89564967', 'CQ', DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `pct3`.`empresa`
-- -----------------------------------------------------
START TRANSACTION;
USE `pct3`;
INSERT INTO `pct3`.`empresa` (`empresa_id`, `nombre_empresa`, `persona_idpersona`) VALUES (DEFAULT, DEFAULT, DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `pct3`.`horario`
-- -----------------------------------------------------
START TRANSACTION;
USE `pct3`;
INSERT INTO `pct3`.`horario` (`horario_id`, `descripcion_horario`) VALUES (DEFAULT, 'Diurno');

COMMIT;


-- -----------------------------------------------------
-- Data for table `pct3`.`puesto`
-- -----------------------------------------------------
START TRANSACTION;
USE `pct3`;
INSERT INTO `pct3`.`puesto` (`puesto_id`, `descripcion_puesto`, `pago_hora_sencilla`, `pago_hora_extra`) VALUES (DEFAULT, 'Administrador', 2500, 5000);

COMMIT;


-- -----------------------------------------------------
-- Data for table `pct3`.`colaborador`
-- -----------------------------------------------------
START TRANSACTION;
USE `pct3`;
INSERT INTO `pct3`.`colaborador` (`empleado_id`, `fecha_contrato`, `fecha_despido`, `observaciones`, `persona_idpersona`, `horario_horario_id`, `puesto_puesto_id`) VALUES (DEFAULT, '2017-02-01', '', '', DEFAULT, DEFAULT, DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `pct3`.`datos_empresa`
-- -----------------------------------------------------
START TRANSACTION;
USE `pct3`;
INSERT INTO `pct3`.`datos_empresa` (`iddatos_empresa`, `empresa_nombre`, `empresa_propietario`, `empresa_sa`, `empresa_cedula_juridica`, `empresa_telefono1`, `empresa_telefono2`, `empresa_direccion`) VALUES (DEFAULT, 'Cabinas El Trópico', 'Cesar Gonzalez', 'Cabinas El Trópico', '1-000-000', '8001-0000', '8001-0001', 'Guatuso');

COMMIT;


-- -----------------------------------------------------
-- Data for table `pct3`.`factura_cabina`
-- -----------------------------------------------------
START TRANSACTION;
USE `pct3`;
INSERT INTO `pct3`.`factura_cabina` (`factura_id`, `cant_dia`, `fecha`, `descuento_factura`, `impuesto_cabina`, `precio_total_cabina`, `cabina_cabina_id`, `persona_idpersona`, `colaborador_empleado_id`, `datos_empresa_iddatos_empresa`, `persona_idpersona1`) VALUES (DEFAULT, 1, '2017-02-01', 0, 0, 10000, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `pct3`.`gasto_operativo`
-- -----------------------------------------------------
START TRANSACTION;
USE `pct3`;
INSERT INTO `pct3`.`gasto_operativo` (`gasto_id`, `descripcion_gasto`, `monto_gasto`, `fecha_gasto`, `factura_gasto`, `colaborador_empleado_id`) VALUES (DEFAULT, 'Gasolina', 10000, '2017-02-01', '151515151', DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `pct3`.`inventario`
-- -----------------------------------------------------
START TRANSACTION;
USE `pct3`;
INSERT INTO `pct3`.`inventario` (`inventario_id`, `nombre_producto`, `cant_producto`, `fecha_compra_producto`, `precio_inventario`, `proveedor_proveedor_id`, `productos_idproductos`) VALUES (DEFAULT, 'Desodorante', 1, '2017-02-01', 1000, 1, DEFAULT);

COMMIT;


-- -----------------------------------------------------
-- Data for table `pct3`.`planilla`
-- -----------------------------------------------------
START TRANSACTION;
USE `pct3`;
INSERT INTO `pct3`.`planilla` (`planilla_id`, `descripcion_planilla`, `fecha_planilla`, `total_hora_sencilla`, `total_hora_extra`, `total_deduc_ccss`, `deducciones`, `monto_pago_planilla`, `colaborador_empleado_id`) VALUES (DEFAULT, 'Semanal', '2017-02-01', 25, 0, 0, 0, 62500, DEFAULT);

COMMIT;

