-- MySQL Script generated by MySQL Workbench
-- Mon Apr 10 11:46:21 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pct3
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pct3` ;

-- -----------------------------------------------------
-- Schema pct3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pct3` DEFAULT CHARACTER SET utf8 ;
USE `pct3` ;

-- -----------------------------------------------------
-- Table `pct3`.`cabina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pct3`.`cabina` ;

CREATE TABLE IF NOT EXISTS `pct3`.`cabina` (
  `cabina_id` SMALLINT(6) NOT NULL AUTO_INCREMENT,
  `descripcion_cabina` VARCHAR(30) NOT NULL,
  `estado_cabina` VARCHAR(45) NOT NULL,
  `precio` FLOAT NOT NULL,
  `tipo_cabina` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cabina_id`),
  UNIQUE INDEX `descripcion_cabina_UNIQUE` (`descripcion_cabina` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8
COMMENT = 'Almacena el nombre de la cabina y actualizará el estado de ocupado a vacio.';


-- -----------------------------------------------------
-- Table `pct3`.`tipo_persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pct3`.`tipo_persona` ;

CREATE TABLE IF NOT EXISTS `pct3`.`tipo_persona` (
  `idtipo_persona` INT(11) NOT NULL AUTO_INCREMENT,
  `desc_persona` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtipo_persona`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pct3`.`persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pct3`.`persona` ;

CREATE TABLE IF NOT EXISTS `pct3`.`persona` (
  `idpersona` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `cedula` BIGINT(20) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `tipo_persona_idtipo_persona` INT(11) NOT NULL,
  PRIMARY KEY (`idpersona`),
  UNIQUE INDEX `cedula_UNIQUE` (`cedula` ASC),
  INDEX `fk_persona_tipo_persona1_idx` (`tipo_persona_idtipo_persona` ASC),
  CONSTRAINT `fk_persona_tipo_persona1`
    FOREIGN KEY (`tipo_persona_idtipo_persona`)
    REFERENCES `pct3`.`tipo_persona` (`idtipo_persona`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pct3`.`cliente_empresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pct3`.`cliente_empresa` ;

CREATE TABLE IF NOT EXISTS `pct3`.`cliente_empresa` (
  `empresa_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `codigo_cliente` VARCHAR(45) NOT NULL,
  `estado_cliente` TINYINT(1) NOT NULL,
  `persona_idpersona` INT(11) NOT NULL,
  PRIMARY KEY (`empresa_id`),
  INDEX `cliente_empresa_FK_idx` (`persona_idpersona` ASC),
  INDEX `persona_idpersona` (`persona_idpersona` ASC),
  CONSTRAINT `fk_cliente_empresa_persona1`
    FOREIGN KEY (`persona_idpersona`)
    REFERENCES `pct3`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pct3`.`horario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pct3`.`horario` ;

CREATE TABLE IF NOT EXISTS `pct3`.`horario` (
  `horario_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `descripcion_horario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`horario_id`),
  UNIQUE INDEX `descripcion_horario` (`descripcion_horario` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pct3`.`puesto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pct3`.`puesto` ;

CREATE TABLE IF NOT EXISTS `pct3`.`puesto` (
  `puesto_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `descripcion_puesto` VARCHAR(45) NOT NULL,
  `pago_hora_sencilla` FLOAT NOT NULL,
  `pago_hora_extra` FLOAT NOT NULL,
  PRIMARY KEY (`puesto_id`),
  UNIQUE INDEX `descripcion_puesto_UNIQUE` (`descripcion_puesto` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pct3`.`colaborador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pct3`.`colaborador` ;

CREATE TABLE IF NOT EXISTS `pct3`.`colaborador` (
  `empleado_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `fecha_contrato` DATE NOT NULL,
  `fecha_despido` DATE NULL DEFAULT NULL,
  `observaciones` VARCHAR(45) NULL DEFAULT NULL,
  `persona_idpersona` INT(11) NOT NULL,
  `puesto_puesto_id` BIGINT(20) UNSIGNED NOT NULL,
  `horario_horario_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`empleado_id`, `persona_idpersona`),
  INDEX `fk_colaborador_persona_idx` (`persona_idpersona` ASC),
  INDEX `fk_colaborador_puesto1_idx` (`puesto_puesto_id` ASC),
  INDEX `fk_colaborador_horario_idx` (`horario_horario_id` ASC),
  CONSTRAINT `fk_colaborador_horario`
    FOREIGN KEY (`horario_horario_id`)
    REFERENCES `pct3`.`horario` (`horario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_colaborador_persona`
    FOREIGN KEY (`persona_idpersona`)
    REFERENCES `pct3`.`persona` (`idpersona`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_colaborador_puesto1`
    FOREIGN KEY (`puesto_puesto_id`)
    REFERENCES `pct3`.`puesto` (`puesto_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pct3`.`factura_cabina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pct3`.`factura_cabina` ;

CREATE TABLE IF NOT EXISTS `pct3`.`factura_cabina` (
  `factura_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `cant_dia` TINYINT(4) NOT NULL,
  `fecha` DATE NOT NULL,
  `impuesto_cabina` FLOAT NOT NULL,
  `precio_total_cabina` BIGINT(20) NOT NULL,
  `cabina_cabina_id` SMALLINT(6) NOT NULL,
  `colaborador_empleado_id` BIGINT(20) NOT NULL,
  `numero_factura` BIGINT(20) NOT NULL,
  `cliente_empresa_empresa_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`factura_id`),
  INDEX `fk_factura_cabina_cabina1_idx` (`cabina_cabina_id` ASC),
  INDEX `fk_factura_cabina_colaborador1_idx` (`colaborador_empleado_id` ASC),
  INDEX `fk_factura_cabina_cliente_empresa1_idx` (`cliente_empresa_empresa_id` ASC),
  CONSTRAINT `fk_factura_cabina_cabina1`
    FOREIGN KEY (`cabina_cabina_id`)
    REFERENCES `pct3`.`cabina` (`cabina_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_factura_cabina_colaborador1`
    FOREIGN KEY (`colaborador_empleado_id`)
    REFERENCES `pct3`.`colaborador` (`empleado_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_factura_cabina_cliente_empresa1`
    FOREIGN KEY (`cliente_empresa_empresa_id`)
    REFERENCES `pct3`.`cliente_empresa` (`empresa_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pct3`.`gasto_operativo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pct3`.`gasto_operativo` ;

CREATE TABLE IF NOT EXISTS `pct3`.`gasto_operativo` (
  `gasto_id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `tipo_gasto` VARCHAR(50) NOT NULL DEFAULT 'planilla o gasto operativo',
  `monto_gasto` MEDIUMINT(9) NOT NULL,
  `fecha_gasto` DATE NOT NULL,
  `factura_gasto` VARCHAR(45) NOT NULL,
  `colaborador_empleado_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`gasto_id`),
  INDEX `fk_gasto_operativo_colaborador1_idx` (`colaborador_empleado_id` ASC),
  CONSTRAINT `fk_gasto_operativo_colaborador1`
    FOREIGN KEY (`colaborador_empleado_id`)
    REFERENCES `pct3`.`colaborador` (`empleado_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 45
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pct3`.`proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pct3`.`proveedor` ;

CREATE TABLE IF NOT EXISTS `pct3`.`proveedor` (
  `idproveedor` INT(11) NOT NULL AUTO_INCREMENT,
  `desc_proveedor` VARCHAR(45) NULL DEFAULT NULL,
  `persona_idpersona` INT(11) NOT NULL,
  PRIMARY KEY (`idproveedor`),
  INDEX `fk_proveedor_persona1_idx` (`persona_idpersona` ASC),
  CONSTRAINT `fk_proveedor_persona1`
    FOREIGN KEY (`persona_idpersona`)
    REFERENCES `pct3`.`persona` (`idpersona`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pct3`.`productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pct3`.`productos` ;

CREATE TABLE IF NOT EXISTS `pct3`.`productos` (
  `idproductos` BIGINT(20) NOT NULL,
  `nombre_producto` VARCHAR(45) NOT NULL,
  `proveedor_idproveedor` INT(11) NOT NULL,
  PRIMARY KEY (`idproductos`),
  INDEX `fk_productos_proveedor1_idx` (`proveedor_idproveedor` ASC),
  CONSTRAINT `fk_productos_proveedor1`
    FOREIGN KEY (`proveedor_idproveedor`)
    REFERENCES `pct3`.`proveedor` (`idproveedor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pct3`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pct3`.`usuario` ;

CREATE TABLE IF NOT EXISTS `pct3`.`usuario` (
  `idusuario` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `password` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `colaborador_empleado_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuario_colaborador1_idx` (`colaborador_empleado_id` ASC),
  CONSTRAINT `fk_usuario_colaborador1`
    FOREIGN KEY (`colaborador_empleado_id`)
    REFERENCES `pct3`.`colaborador` (`empleado_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
ROW_FORMAT = COMPACT;

USE `pct3` ;

-- -----------------------------------------------------
-- procedure actualizar_precio_doble
-- -----------------------------------------------------

USE `pct3`;
DROP procedure IF EXISTS `pct3`.`actualizar_precio_doble`;

DELIMITER $$
USE `pct3`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `actualizar_precio_doble`(IN `precio_doble` FLOAT)
BEGIN
UPDATE `cabina` SET `precio`= precio_doble WHERE `tipo_cabina` = 'Doble';

END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure actualizar_precio_sencilla
-- -----------------------------------------------------

USE `pct3`;
DROP procedure IF EXISTS `pct3`.`actualizar_precio_sencilla`;

DELIMITER $$
USE `pct3`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `actualizar_precio_sencilla`(IN `precio_doble` FLOAT)
BEGIN
UPDATE `cabina` SET `precio`= precio_doble WHERE `tipo_cabina` = 'Sencilla';

END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
