-- MySQL Script generated by MySQL Workbench
-- dom 05 feb 2017 18:55:30 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema PCT2
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `PCT2` ;

-- -----------------------------------------------------
-- Schema PCT2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PCT2` DEFAULT CHARACTER SET utf8 ;
USE `PCT2` ;

-- -----------------------------------------------------
-- Table `PCT2`.`precio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PCT2`.`precio` ;

CREATE TABLE IF NOT EXISTS `PCT2`.`precio` (
  `precio_id` TINYINT(4) NOT NULL AUTO_INCREMENT,
  `descripcion_precio` VARCHAR(30) NOT NULL,
  `monto_precio` FLOAT NOT NULL,
  PRIMARY KEY (`precio_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `PCT2`.`cabina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PCT2`.`cabina` ;

CREATE TABLE IF NOT EXISTS `PCT2`.`cabina` (
  `cabina_id` SMALLINT(6) NOT NULL AUTO_INCREMENT,
  `descripcion_cabina` VARCHAR(30) NOT NULL,
  `estado_cabina` TINYINT(4) NOT NULL,
  `precio_cabina` INT(11) NOT NULL,
  `ocupacion_id` INT NULL,
  `precio_id` INT NULL,
  `precio_precio_id` TINYINT(4) NOT NULL,
  PRIMARY KEY (`cabina_id`),
  INDEX `fk_cabinas_precio1_idx` (`precio_precio_id` ASC),
  CONSTRAINT `fk_cabinas_precio1`
    FOREIGN KEY (`precio_precio_id`)
    REFERENCES `PCT2`.`precio` (`precio_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `PCT2`.`empresa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PCT2`.`empresa` ;

CREATE TABLE IF NOT EXISTS `PCT2`.`empresa` (
  `empresa_id` BIGINT(20) UNSIGNED NOT NULL,
  `nombre_empresa` VARCHAR(30) NOT NULL,
  `cedula_juridica` VARCHAR(30) NOT NULL,
  `telefono1_empresa` INT(11) NOT NULL,
  `telefono2_empresa` INT(11) NOT NULL,
  `descripcion_empresa` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`empresa_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `PCT2`.`cliente_empresarial`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PCT2`.`cliente_empresarial` ;

CREATE TABLE IF NOT EXISTS `PCT2`.`cliente_empresarial` (
  `cliente_id_empresarial` INT NOT NULL AUTO_INCREMENT,
  `cliente_id` BIGINT(20) UNSIGNED NOT NULL,
  `empresa_id` INT(11) NOT NULL,
  `empresa_Empresa_id` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`cliente_id_empresarial`),
  INDEX `fk_clientes_empresarial_empresa1_idx` (`empresa_Empresa_id` ASC),
  CONSTRAINT `fk_clientes_empresarial_empresa1`
    FOREIGN KEY (`empresa_Empresa_id`)
    REFERENCES `PCT2`.`empresa` (`empresa_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `PCT2`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PCT2`.`cliente` ;

CREATE TABLE IF NOT EXISTS `PCT2`.`cliente` (
  `cliente_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre_cliente` VARCHAR(45) NOT NULL,
  `apellido_cliente` VARCHAR(45) NOT NULL,
  `cedula_cliente` VARCHAR(20) NOT NULL,
  `clientes_empresarial_cliente_id_empresarial` INT NOT NULL,
  `apellido2_cliente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cliente_id`),
  INDEX `fk_cliente_clientes_empresarial1_idx` (`clientes_empresarial_cliente_id_empresarial` ASC),
  CONSTRAINT `fk_cliente_clientes_empresarial1`
    FOREIGN KEY (`clientes_empresarial_cliente_id_empresarial`)
    REFERENCES `PCT2`.`cliente_empresarial` (`cliente_id_empresarial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `PCT2`.`facturar_cabina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PCT2`.`facturar_cabina` ;

CREATE TABLE IF NOT EXISTS `PCT2`.`facturar_cabina` (
  `factura_id` BIGINT(20) UNSIGNED NOT NULL,
  `cabina_id` INT(11) NOT NULL,
  `cant_dia` TINYINT(4) NULL DEFAULT NULL,
  `fecha` DATE NOT NULL,
  `cliente_id` INT(11) NULL DEFAULT NULL,
  `precio_cabina` INT(11) NOT NULL,
  `impuesto_cabina` FLOAT NULL,
  `precio_total_cabina` INT(11) NOT NULL,
  `cliente_cliente_id` BIGINT(20) UNSIGNED NOT NULL,
  `cabinas_cabina_id` SMALLINT(6) NOT NULL,
  `empleado_id` VARCHAR(45) NULL,
  PRIMARY KEY (`factura_id`),
  INDEX `fk_facturar_cabina_cliente1_idx` (`cliente_cliente_id` ASC),
  INDEX `fk_facturar_cabina_cabinas1_idx` (`cabinas_cabina_id` ASC),
  CONSTRAINT `fk_facturar_cabina_cliente1`
    FOREIGN KEY (`cliente_cliente_id`)
    REFERENCES `PCT2`.`cliente` (`cliente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_facturar_cabina_cabinas1`
    FOREIGN KEY (`cabinas_cabina_id`)
    REFERENCES `PCT2`.`cabina` (`cabina_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `PCT2`.`puesto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PCT2`.`puesto` ;

CREATE TABLE IF NOT EXISTS `PCT2`.`puesto` (
  `puesto_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `empleado_id` INT(11) NOT NULL,
  `horario_id` INT(11) NOT NULL,
  `horario_horario_id` BIGINT(20) UNSIGNED NOT NULL,
  `descripcion_puesto` VARCHAR(30) NOT NULL,
  `salario_base` INT(11) NOT NULL,
  `pago_hora_sencilla` FLOAT NOT NULL,
  `pago_hora_extra` FLOAT NOT NULL,
  PRIMARY KEY (`puesto_id`, `horario_horario_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `PCT2`.`empleado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PCT2`.`empleado` ;

CREATE TABLE IF NOT EXISTS `PCT2`.`empleado` (
  `empleado_id` BIGINT(20) UNSIGNED NOT NULL,
  `nombre_empleado` VARCHAR(30) NOT NULL,
  `apellido_empleado` VARCHAR(30) NOT NULL,
  `cedula_empleado` VARCHAR(20) NOT NULL,
  `direccion` VARCHAR(50) NOT NULL,
  `telefono_empleado` INT(11) NOT NULL,
  `fecha_contrato` DATE NOT NULL,
  `facturar_cabina_factura_id` BIGINT(20) UNSIGNED NOT NULL,
  `puesto_puesto_id` BIGINT(20) UNSIGNED NOT NULL,
  `puesto_horario_horario_id` BIGINT(20) UNSIGNED NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `fecha_despido` DATE NULL,
  `estado_empleado` VARCHAR(45) NULL,
  PRIMARY KEY (`empleado_id`),
  INDEX `fk_empleado_facturar_cabina1_idx` (`facturar_cabina_factura_id` ASC),
  INDEX `fk_empleado_puesto1_idx` (`puesto_puesto_id` ASC, `puesto_horario_horario_id` ASC),
  CONSTRAINT `fk_empleado_facturar_cabina1`
    FOREIGN KEY (`facturar_cabina_factura_id`)
    REFERENCES `PCT2`.`facturar_cabina` (`factura_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleado_puesto1`
    FOREIGN KEY (`puesto_puesto_id` , `puesto_horario_horario_id`)
    REFERENCES `PCT2`.`puesto` (`puesto_id` , `horario_horario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `PCT2`.`tipo_gasto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PCT2`.`tipo_gasto` ;

CREATE TABLE IF NOT EXISTS `PCT2`.`tipo_gasto` (
  `id_tipo_gasto` INT NOT NULL,
  `descripcion_tipo_gasto` VARCHAR(45) NULL,
  PRIMARY KEY (`id_tipo_gasto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PCT2`.`gasto_operativo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PCT2`.`gasto_operativo` ;

CREATE TABLE IF NOT EXISTS `PCT2`.`gasto_operativo` (
  `gasto_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `descripcion_gasto` VARCHAR(50) NOT NULL,
  `monto_gasto` MEDIUMINT(9) NOT NULL,
  `fecha_gasto` DATE NULL,
  `factura_gasto` VARCHAR(45) NULL,
  `tipo_gasto_id` INT NULL,
  `empleado_id` INT NULL,
  `empleado_empleado_id` BIGINT(20) UNSIGNED NOT NULL,
  `tipo_gasto_id_tipo_gasto` INT NOT NULL,
  PRIMARY KEY (`gasto_id`),
  INDEX `fk_gastos_operativos_empleado1_idx` (`empleado_empleado_id` ASC),
  INDEX `fk_gastos_operativos_tipo_gasto1_idx` (`tipo_gasto_id_tipo_gasto` ASC),
  CONSTRAINT `fk_gastos_operativos_empleado1`
    FOREIGN KEY (`empleado_empleado_id`)
    REFERENCES `PCT2`.`empleado` (`empleado_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gastos_operativos_tipo_gasto1`
    FOREIGN KEY (`tipo_gasto_id_tipo_gasto`)
    REFERENCES `PCT2`.`tipo_gasto` (`id_tipo_gasto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `PCT2`.`horario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PCT2`.`horario` ;

CREATE TABLE IF NOT EXISTS `PCT2`.`horario` (
  `horario_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `entrada` VARCHAR(30) NOT NULL,
  `salida` VARCHAR(30) NOT NULL,
  `descanso` VARCHAR(30) NOT NULL,
  `descripcion_horario` VARCHAR(45) NULL,
  `monto_hora_sencilla` FLOAT NULL,
  `monto_hora_extra` FLOAT NULL,
  `puesto_puesto_id` BIGINT(20) UNSIGNED NOT NULL,
  `puesto_horario_Horario_ID` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`horario_id`),
  INDEX `fk_horario_puesto1_idx` (`puesto_puesto_id` ASC, `puesto_horario_Horario_ID` ASC),
  CONSTRAINT `fk_horario_puesto1`
    FOREIGN KEY (`puesto_puesto_id` , `puesto_horario_Horario_ID`)
    REFERENCES `PCT2`.`puesto` (`puesto_id` , `horario_horario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `PCT2`.`proveedor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PCT2`.`proveedor` ;

CREATE TABLE IF NOT EXISTS `PCT2`.`proveedor` (
  `proveedor_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre_proveedor` VARCHAR(30) NOT NULL,
  `contacto_proveedor` VARCHAR(45) NULL,
  `telefono1_proveedor` VARCHAR(45) NULL,
  `telefono2_proveedor` VARCHAR(45) NULL,
  PRIMARY KEY (`proveedor_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `PCT2`.`inventario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PCT2`.`inventario` ;

CREATE TABLE IF NOT EXISTS `PCT2`.`inventario` (
  `inventario_id` INT(11) NOT NULL AUTO_INCREMENT,
  `producto_id` INT(11) NULL DEFAULT NULL,
  `proveedor_id` INT(11) NULL DEFAULT NULL,
  `nombre_producto` VARCHAR(30) NOT NULL,
  `cant_producto` INT(11) NOT NULL,
  `fecha_compra_producto` DATE NOT NULL,
  `precio_inventario` FLOAT NOT NULL,
  `id_proveedor` INT NULL,
  `proveedor_proveedor_id` BIGINT(20) UNSIGNED NOT NULL,
  `empleado_id` INT NULL,
  `empleado_empleado_id` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`inventario_id`),
  INDEX `fk_inventario_proveedor1_idx` (`proveedor_proveedor_id` ASC),
  INDEX `fk_inventario_empleado1_idx` (`empleado_empleado_id` ASC),
  CONSTRAINT `fk_inventario_proveedor1`
    FOREIGN KEY (`proveedor_proveedor_id`)
    REFERENCES `PCT2`.`proveedor` (`proveedor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inventario_empleado1`
    FOREIGN KEY (`empleado_empleado_id`)
    REFERENCES `PCT2`.`empleado` (`empleado_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `PCT2`.`planilla`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PCT2`.`planilla` ;

CREATE TABLE IF NOT EXISTS `PCT2`.`planilla` (
  `planilla_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `descripcion_planilla` VARCHAR(30) NOT NULL,
  `puesto_id` INT(11) NOT NULL,
  `empleado_id` INT(11) NOT NULL,
  `fecha_planilla` DATE NOT NULL,
  `total_hora_sencilla` FLOAT NOT NULL,
  `total_hora_extra` FLOAT NOT NULL,
  `total_deduc_ccss` FLOAT NOT NULL,
  `deducciones` FLOAT NOT NULL,
  `monto_pago_planilla` FLOAT NOT NULL,
  `empleado_id` INT NULL,
  `empleado_empleado_id` BIGINT(20) UNSIGNED NOT NULL,
  `id_tipo_gasto` INT NULL,
  `tipo_gasto_id_tipo_gasto` INT NOT NULL,
  PRIMARY KEY (`planilla_id`),
  INDEX `fk_planilla_empleado1_idx` (`empleado_empleado_id` ASC),
  INDEX `fk_planilla_tipo_gasto1_idx` (`tipo_gasto_id_tipo_gasto` ASC),
  CONSTRAINT `fk_planilla_empleado1`
    FOREIGN KEY (`empleado_empleado_id`)
    REFERENCES `PCT2`.`empleado` (`empleado_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_planilla_tipo_gasto1`
    FOREIGN KEY (`tipo_gasto_id_tipo_gasto`)
    REFERENCES `PCT2`.`tipo_gasto` (`id_tipo_gasto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `PCT2`.`tipo_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PCT2`.`tipo_usuario` ;

CREATE TABLE IF NOT EXISTS `PCT2`.`tipo_usuario` (
  `id_tipo_usuario` INT NOT NULL AUTO_INCREMENT,
  `descripcion_tipo_usuario` VARCHAR(45) NULL,
  PRIMARY KEY (`id_tipo_usuario`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
