/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.cabinas;

import controller.conexionDB;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import model.Pantalla_principal;

/**
 *
 * @author ace
 */
public class SeleccionarCabina extends javax.swing.JFrame {

    /**
     * Creates new form SeleccionarCabina
     */
    // Se crea un array de botones
    private final List<JButton> botones;
    // Se agrega un indice para prueba del nombre, aunque debería leer el nombre de la cabina.

    Connection con = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    JButton b[];
    String cambiarFuncion[] = new String[6];

    public SeleccionarCabina() {
        initComponents();
agregarCabinas.setOpaque(false);
opciones.setOpaque(false);
        initComponents();
        con = conexionDB.conexionDB();

        setLocationRelativeTo(null);
        botones = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgOpciones = new javax.swing.ButtonGroup();
        opciones = new javax.swing.JPanel();
        Ocupado = new javax.swing.JRadioButton();
        Todos = new javax.swing.JRadioButton();
        Sencilla = new javax.swing.JRadioButton();
        Vacio = new javax.swing.JRadioButton();
        Limpieza = new javax.swing.JRadioButton();
        Bloqueado = new javax.swing.JRadioButton();
        Doble = new javax.swing.JRadioButton();
        agregarCabinas = new javax.swing.JPanel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgOpciones.add(Ocupado);
        Ocupado.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        Ocupado.setForeground(new java.awt.Color(251, 251, 251));
        Ocupado.setText("Ocupado");
        Ocupado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OcupadoActionPerformed(evt);
            }
        });

        Todos.setBackground(new java.awt.Color(0, 0, 51));
        bgOpciones.add(Todos);
        Todos.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        Todos.setForeground(new java.awt.Color(251, 251, 251));
        Todos.setText("Todos");
        Todos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TodosActionPerformed(evt);
            }
        });

        bgOpciones.add(Sencilla);
        Sencilla.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        Sencilla.setForeground(new java.awt.Color(251, 251, 251));
        Sencilla.setText("Hab. Doble");
        Sencilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SencillaActionPerformed(evt);
            }
        });

        bgOpciones.add(Vacio);
        Vacio.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        Vacio.setForeground(new java.awt.Color(251, 251, 251));
        Vacio.setText("Vacio");
        Vacio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VacioActionPerformed(evt);
            }
        });

        bgOpciones.add(Limpieza);
        Limpieza.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        Limpieza.setForeground(new java.awt.Color(251, 251, 251));
        Limpieza.setText("Limpieza");
        Limpieza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiezaActionPerformed(evt);
            }
        });

        bgOpciones.add(Bloqueado);
        Bloqueado.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        Bloqueado.setForeground(new java.awt.Color(251, 251, 251));
        Bloqueado.setText("Bloqueado");
        Bloqueado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BloqueadoActionPerformed(evt);
            }
        });

        bgOpciones.add(Doble);
        Doble.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        Doble.setForeground(new java.awt.Color(251, 251, 251));
        Doble.setText("Hab. Sencilla");
        Doble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DobleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout opcionesLayout = new javax.swing.GroupLayout(opciones);
        opciones.setLayout(opcionesLayout);
        opcionesLayout.setHorizontalGroup(
            opcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(opcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(opcionesLayout.createSequentialGroup()
                        .addGroup(opcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Sencilla)
                            .addComponent(Doble)
                            .addComponent(Ocupado)
                            .addComponent(Vacio)
                            .addComponent(Todos))
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addGroup(opcionesLayout.createSequentialGroup()
                        .addGroup(opcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Limpieza)
                            .addComponent(Bloqueado))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        opcionesLayout.setVerticalGroup(
            opcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(opcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Todos)
                .addGap(18, 18, 18)
                .addComponent(Ocupado)
                .addGap(18, 18, 18)
                .addComponent(Vacio)
                .addGap(18, 18, 18)
                .addComponent(Limpieza)
                .addGap(18, 18, 18)
                .addComponent(Bloqueado)
                .addGap(18, 18, 18)
                .addComponent(Doble)
                .addGap(18, 18, 18)
                .addComponent(Sencilla)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        getContentPane().add(opciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 370));

        agregarCabinas.setLayout(new java.awt.GridLayout(0, 3));
        getContentPane().add(agregarCabinas, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 580, 370));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/FondoAzul.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 742, 367));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OcupadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OcupadoActionPerformed
        // TODO add your handling code here:
        agregarCabinas.removeAll();
        Get_Data_Ocupado();
    }//GEN-LAST:event_OcupadoActionPerformed

    private void TodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TodosActionPerformed
        // TODO add your handling code here:
        agregarCabinas.removeAll();
        Get_Data();
    }//GEN-LAST:event_TodosActionPerformed

    private void VacioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VacioActionPerformed
        // TODO add your handling code here:
        agregarCabinas.removeAll();
        Get_Data_Vacio();
    }//GEN-LAST:event_VacioActionPerformed

    private void LimpiezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiezaActionPerformed
        // TODO add your handling code here:
        agregarCabinas.removeAll();
        Get_Data_Limpieza();
    }//GEN-LAST:event_LimpiezaActionPerformed

    private void BloqueadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BloqueadoActionPerformed
        // TODO add your handling code here:
        agregarCabinas.removeAll();
        Get_Data_Bloqueada();
    }//GEN-LAST:event_BloqueadoActionPerformed

    private void DobleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DobleActionPerformed
        // TODO add your handling code here:
        agregarCabinas.removeAll();
        Get_Data_Sencilla();
    }//GEN-LAST:event_DobleActionPerformed

    private void SencillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SencillaActionPerformed
        // TODO add your handling code here:
        agregarCabinas.removeAll();
        Get_Data_Doble();
    }//GEN-LAST:event_SencillaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionarCabina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new SeleccionarCabina().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Bloqueado;
    private javax.swing.JRadioButton Doble;
    private javax.swing.JRadioButton Limpieza;
    private javax.swing.JRadioButton Ocupado;
    private javax.swing.JRadioButton Sencilla;
    private javax.swing.JRadioButton Todos;
    private javax.swing.JRadioButton Vacio;
    private javax.swing.JPanel agregarCabinas;
    private javax.swing.ButtonGroup bgOpciones;
    private javax.swing.JLabel fondo;
    private javax.swing.JPanel opciones;
    // End of variables declaration//GEN-END:variables

    private void Get_Data() {
        String sql = "SELECT Count(*) FROM `cabina`";
        try {
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            rs.next();
            System.out.println("numero de renglones: " + rs.getString(1));
            int valor = Integer.parseInt(rs.getString(1));
            b = new JButton[valor];
            for (int i = 0; i < valor; i++) {
                b[i] = new JButton("Cabina " + (i + 1));
                agregarCabinas.add(b[i]);
                b[i].setSize(60, 60);
            }
            agregarCabinas.updateUI();
        } catch (SQLException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void Get_Data_Ocupado() {
        String sql = "SELECT Count(*) FROM `cabina` WHERE estado_cabina_idestado_cabina = '1'";
        try {

            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            rs.next();
       
            System.out.println("numero de renglones: " + rs.getString(1));

            int valor = Integer.parseInt(rs.getString(1));
            b = new JButton[valor];
            for (int i = 0; i < valor; i++) {
                b[i] = new JButton("Cabina " + (i + 1));
                agregarCabinas.add(b[i]);
                b[i].setBackground(Color.red);
                b[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/CRUD/edit.png"))); // NOI18N
                b[i].addActionListener((ActionEvent e) -> {
                    Pantalla_principal principal = new Pantalla_principal();
                    principal.setVisible(true);
                    System.out.println("Juana");
                });
            }
            agregarCabinas.updateUI();
        } catch (SQLException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }
    
    private void Get_Data_Vacio() {
        String sql = "SELECT Count(*) FROM `cabina` WHERE estado_cabina_idestado_cabina = '2'";
        try {

            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            rs.next();
            
            System.out.println("numero de renglones: " + rs.getString(1));

            int valor = Integer.parseInt(rs.getString(1));
            b = new JButton[valor];

            for (int i = 0; i < valor; i++) {
                b[i] = new JButton("Cabina " + (i + 1));
                agregarCabinas.add(b[i]);
                b[i].setBackground(Color.GREEN);
                b[i].addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.out.println("Hellen");
            }
        });
            }
            agregarCabinas.updateUI();
        } catch (SQLException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }
    
    private void Get_Data_Limpieza() {
        String sql = "SELECT Count(*) FROM `cabina` WHERE estado_cabina_idestado_cabina = '3'";
        try {

            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            rs.next();
 
            System.out.println("numero de renglones: " + rs.getString(1));

            int valor = Integer.parseInt(rs.getString(1));
            b = new JButton[valor];

            for (int i = 0; i < valor; i++) {
                b[i] = new JButton("Cabina " + (i + 1));
                agregarCabinas.add(b[i]);b[i].setBackground(Color.YELLOW);
                b[i].addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.out.println("Juana");
            }
        });
            }
            agregarCabinas.updateUI();
        } catch (SQLException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }
    
    private void Get_Data_Bloqueada() {
        String sql = "SELECT Count(*) FROM `cabina` WHERE estado_cabina_idestado_cabina = '4'";
        try {

            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            rs.next();
            for (int i = 0; i < 10; i++) {

            }
            System.out.println("numero de renglones: " + rs.getString(1));

            int valor = Integer.parseInt(rs.getString(1));
            b = new JButton[valor];

            for (int i = 0; i < valor; i++) {
                b[i] = new JButton("Cabina " + (i + 1));
                agregarCabinas.add(b[i]);
                for (Iterator<JButton> it = botones.iterator(); it.hasNext();) {
                    JButton boton;
                    boton = it.next();
                    b[i].addActionListener((ActionEvent e) -> {
                        System.out.println(b[1].getText());
                    });
                }
            }
            agregarCabinas.updateUI();
        } catch (SQLException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }
    
    private void Get_Data_Sencilla() {
        String sql = "SELECT Count(*) FROM `cabina` WHERE `precio_precio_id` = '1'";
        try {

            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            rs.next();
            for (int i = 0; i < 10; i++) {

            }
            System.out.println("numero de renglones: " + rs.getString(1));

            int valor = Integer.parseInt(rs.getString(1));
            b = new JButton[valor];

            for (int i = 0; i < valor; i++) {
                b[i] = new JButton("Cabina " + (i + 1));
                ImageIcon icon= new ImageIcon("/view/icons/one-bed-for-two.png");
                b[i].setIcon(icon);
                agregarCabinas.add(b[i]);
                b[i].addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.out.println("Juana");
            }
        });
            
                
            }
            agregarCabinas.updateUI();
        } catch (SQLException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }
    
    private void Get_Data_Doble() {
        String sql = "SELECT Count(*) FROM `cabina` WHERE `precio_precio_id` = '2'";
        try {

            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            rs.next();
            for (int i = 0; i < 10; i++) {

            }
            System.out.println("numero de renglones: " + rs.getString(1));

            int valor = Integer.parseInt(rs.getString(1));
            b = new JButton[valor];

            for (int i = 0; i < valor; i++) {
                b[i] = new JButton("Cabina " + (i + 1));
                
                ImageIcon icon= new ImageIcon("/view/icons/one-bed-for-two.png");
                b[i].setIcon(icon);
                agregarCabinas.add(b[i]);
                for (Iterator<JButton> it = botones.iterator(); it.hasNext();) {
                    JButton boton;
                    boton = it.next();
                    b[i].addActionListener((ActionEvent e) -> {
                        System.out.println(b[1].getText());
                    });
                }
            }
            agregarCabinas.updateUI();
        } catch (SQLException | NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }
}
