/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.DBConnection;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Locale;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Eisner López Acevedo <eisner.lopez at gmail.com>
 */
public final class Frm_NuevaFactura extends javax.swing.JInternalFrame {

    /**
     * Creates new form Frm_NuevaFactura
     */
    Connection con = null;
    
    ResultSet rs = null;
    PreparedStatement pst = null;
    ResultSet rs2 = null;
    PreparedStatement pst2 = null;
    
    
    
    
    DateFormat df = DateFormat.getDateInstance();
    public String Valor;
    //declarar static e instanciarla en tu contructor`
    static DefaultComboBoxModel modeloTipoPersona;

    public Frm_NuevaFactura() {
        initComponents();
        con = DBConnection.getConnection();
        nCabina.setText(Seleccionar_Cabina_frm.ps_nombreCabina);
        nombreEmpleado.setText(Login_frm.ps_NombreEmpleado);
        idEmpleado.setText(Login_frm.ps_idEmpleado);
        //idCabina.setVisible(false);
        fechaActual();
        fechas();
        modeloTipoPersona = new DefaultComboBoxModel();
        llena_comboPersona(); // llenar los datos al ejecutar el programa
    }

    public void llena_comboPersona() { // static para poder llamarlo desde el otro frame o JDialog
        try {
            modeloTipoPersona.removeAllElements(); // eliminamos lo elementos
            Statement stmt;
            stmt = con.createStatement();
            String queryComboEstado = "SELECT "
                    + "empresa_id, codigo_cliente, nombre "
                    + "FROM "
                    + "pct3.cliente_empresa "
                    + "INNER JOIN "
                    + "pct3.persona ON cliente_empresa.persona_idpersona = persona.idpersona";
            rs = stmt.executeQuery(queryComboEstado);
            while (rs.next()) {
                modeloTipoPersona.addElement(rs.getString("nombre"));
                codigoCliente.setText(rs.getString("empresa_id"));
                JOptionPane.showMessageDialog(this, rs.getString("empresa_id"));
            }
            cmb_clienteEmpresa.setModel(modeloTipoPersona); // seteamos el modelo y se cargan los datos

        } catch (HeadlessException | SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }

    public void fechas() {
        Date h = new Date();
        SimpleDateFormat formato_Fecha;
        formato_Fecha = new SimpleDateFormat("yyyy/MM/dd", Locale.getDefault());
        String date = new SimpleDateFormat("yyyy/MM/dd").format(new Date());
        SimpleDateFormat formato_Hora;
        formato_Hora = new SimpleDateFormat("HH:mm:ss a", Locale.getDefault());
        //formato_Fecha.format(h)) Imprime el tiempo formateado 
        Valor = date;
        fechaEntrada.setText(Valor);
    }

    public void fechaActual() {
        Date hoy;
        hoy = new Date();
        String date = new SimpleDateFormat("yyyy/MM/dd", Locale.getDefault()).format(new Date());
//        jDateChooser1.setDateFormatString(date);
//        jDateChooser1.setDate(hoy);
//        Valor = jDateChooser1.getDateFormatString();
        System.out.println(Valor);
        fechaEntrada.setText(Valor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        CantidadDias = new javax.swing.JFormattedTextField();
        lblCantDias = new javax.swing.JLabel();
        fechaEntrada = new javax.swing.JLabel();
        lblFechaEntrada = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fechaSalida = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Precio = new javax.swing.JFormattedTextField();
        cmb_clienteEmpresa = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        Precio1 = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblImpuesto = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        impuesto = new javax.swing.JTextField();
        subTotal = new javax.swing.JTextField();
        precioTotal = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        nombreCliente = new javax.swing.JLabel();
        idCliente = new javax.swing.JLabel();
        idCabina = new javax.swing.JLabel();
        idEmpleado = new javax.swing.JLabel();
        codigoCliente = new javax.swing.JLabel();
        idCabina1 = new javax.swing.JLabel();
        nombreCliente1 = new javax.swing.JLabel();
        idEmpleado1 = new javax.swing.JLabel();
        nombreEmpleado = new javax.swing.JLabel();
        lblRegresar = new javax.swing.JLabel();
        lblFacturar = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblVaciar = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        borrar = new javax.swing.JButton();
        guardar = new javax.swing.JButton();
        volver = new javax.swing.JButton();
        nCabina = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Facturar");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Hack", 1, 14)); // NOI18N
        jLabel2.setText("Nombre Cliente");

        CantidadDias.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0"))));
        CantidadDias.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                CantidadDiasFocusLost(evt);
            }
        });
        CantidadDias.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CantidadDiasKeyPressed(evt);
            }
        });

        lblCantDias.setText("Cantidad de Días:");

        fechaEntrada.setFont(new java.awt.Font("Hack", 1, 14)); // NOI18N
        fechaEntrada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fechaEntrada.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblFechaEntrada.setText("Fecha Entrada:");

        jLabel3.setText("Fecha Salida:");

        fechaSalida.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Hack", 1, 14)); // NOI18N
        jLabel1.setText("Precio:");

        Precio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0"))));
        Precio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PrecioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PrecioFocusLost(evt);
            }
        });

        cmb_clienteEmpresa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_clienteEmpresa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_clienteEmpresaItemStateChanged(evt);
            }
        });
        cmb_clienteEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_clienteEmpresaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Hack", 1, 14)); // NOI18N
        jLabel4.setText("N° Factura");

        Precio1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0"))));
        Precio1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Precio1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Precio1FocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCantDias)
                    .addComponent(fechaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CantidadDias, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblFechaEntrada)
                        .addGap(113, 113, 113)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fechaSalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(Precio)))
                    .addComponent(cmb_clienteEmpresa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(168, 168, 168))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Precio1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addComponent(jLabel2)
                    .addContainerGap(691, Short.MAX_VALUE)))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {CantidadDias, Precio, Precio1, jLabel1, jLabel4});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(cmb_clienteEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaEntrada)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 5, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCantDias)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CantidadDias, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Precio)
                        .addComponent(Precio1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(jLabel2)
                    .addContainerGap(126, Short.MAX_VALUE)))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {CantidadDias, Precio, Precio1, jLabel1, jLabel4});

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblImpuesto.setFont(new java.awt.Font("Hack", 1, 14)); // NOI18N
        lblImpuesto.setText("Impuesto:");

        jLabel9.setFont(new java.awt.Font("Hack", 1, 14)); // NOI18N
        jLabel9.setText("Total:");

        jLabel10.setFont(new java.awt.Font("Hack", 1, 14)); // NOI18N
        jLabel10.setText("Sub Total:");

        impuesto.setFont(new java.awt.Font("Hack", 1, 14)); // NOI18N
        impuesto.setEnabled(false);

        subTotal.setFont(new java.awt.Font("Hack", 1, 14)); // NOI18N
        subTotal.setEnabled(false);

        precioTotal.setFont(new java.awt.Font("Hack", 1, 14)); // NOI18N
        precioTotal.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImpuesto)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(impuesto)
                    .addComponent(subTotal)
                    .addComponent(precioTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                .addContainerGap(296, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImpuesto)
                    .addComponent(impuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(31, 31, 31))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(precioTotal)
                        .addContainerGap())))
        );

        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        nombreCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreCliente.setText("nombreCliente");

        idCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        idCliente.setText("idCliente");

        idCabina.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        idCabina.setText("idCabina");

        idEmpleado.setText("idEmpleado");

        codigoCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        codigoCliente.setText("idCliente");

        idCabina1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        idCabina1.setText("idCabina");

        nombreCliente1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreCliente1.setText("nombreCliente");

        idEmpleado1.setText("idEmpleado");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreCliente)
                            .addComponent(nombreCliente1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(idCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(idCabina, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(codigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(idCabina1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idEmpleado1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {idCabina, idCliente, idEmpleado, nombreCliente});

        jPanel4Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {codigoCliente, idCabina1, idEmpleado1, nombreCliente1});

        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idCliente)
                    .addComponent(nombreCliente)
                    .addComponent(idCabina)
                    .addComponent(idEmpleado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreCliente1)
                    .addComponent(idEmpleado1)
                    .addComponent(idCabina1)
                    .addComponent(codigoCliente)))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {idCabina, idCliente, idEmpleado, nombreCliente});

        nombreEmpleado.setFont(new java.awt.Font("Hack", 1, 14)); // NOI18N
        nombreEmpleado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreEmpleado.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.darkGray));

        lblRegresar.setFont(new java.awt.Font("Hack", 1, 12)); // NOI18N
        lblRegresar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegresar.setText("Regresar");

        lblFacturar.setFont(new java.awt.Font("Hack", 1, 12)); // NOI18N
        lblFacturar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFacturar.setText("Facturar");
        lblFacturar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFacturarMouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Hack", 1, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Nombre Cabina");
        jLabel14.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.darkGray));

        lblVaciar.setFont(new java.awt.Font("Hack", 1, 12)); // NOI18N
        lblVaciar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVaciar.setText("Vaciar");

        jLabel16.setFont(new java.awt.Font("Hack", 1, 12)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Nombre Colaborador");
        jLabel16.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.darkGray));

        borrar.setBackground(new java.awt.Color(204, 204, 204));
        borrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/compose_64px.png"))); // NOI18N
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });

        guardar.setBackground(new java.awt.Color(204, 204, 204));
        guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/book_64px.png"))); // NOI18N
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/Inicio.png"))); // NOI18N
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        nCabina.setFont(new java.awt.Font("Hack", 1, 14)); // NOI18N
        nCabina.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nCabina.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.darkGray));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVaciar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nCabina, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFacturar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(volver, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {borrar, guardar, nCabina, nombreEmpleado, volver});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVaciar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFacturar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(borrar)
                    .addComponent(guardar)
                    .addComponent(volver)
                    .addComponent(nCabina, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {borrar, guardar, nCabina, nombreEmpleado, volver});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CantidadDiasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CantidadDiasFocusLost
        // TODO add your handling code here:
        Calendar c1 = GregorianCalendar.getInstance();
        System.out.println("Fecha actual: " + c1.getTime().toLocaleString());
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
        System.out.println("Fecha Formateada: " + sdf.format(c1.getTime()));
        sdf = new SimpleDateFormat("yyyy/MM/dd");
        System.out.println("Fecha Formateada: " + sdf.format(c1.getTime()));
        int valorDias = Integer.parseInt(CantidadDias.getText());
        if (CantidadDias.getText() == null) {
            JOptionPane.showMessageDialog(null, "Ingrese un valor mayor a 1");
            CantidadDias.requestFocus();
        }
        System.out.println("" + valorDias);
        c1.add(Calendar.DATE, valorDias);
        System.out.println("Fecha Formateada: " + sdf.format(c1.getTime()));
        fechaSalida.setText(sdf.format(c1.getTime()));
    }//GEN-LAST:event_CantidadDiasFocusLost

    private void CantidadDiasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CantidadDiasKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_CantidadDiasKeyPressed

    private void PrecioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PrecioFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecioFocusGained

    private void PrecioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PrecioFocusLost
        // TODO add your handling code here:
        int montoImpuesto, subt, montoTotal;
        montoTotal = Integer.parseInt(Precio.getText()) * Integer.parseInt(CantidadDias.getText());
        montoImpuesto = (int) (montoTotal * 0.13);
        subt = montoTotal - montoImpuesto;
        impuesto.setText(String.valueOf(montoImpuesto));
        precioTotal.setText(String.valueOf(montoTotal));
        subTotal.setText(String.valueOf(subt));
    }//GEN-LAST:event_PrecioFocusLost

    private void lblFacturarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFacturarMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_lblFacturarMouseClicked

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        // TODO add your handling code here:

        CantidadDias.setText("");
        impuesto.setText("");
        subTotal.setText("");
        precioTotal.setText("");
    }//GEN-LAST:event_borrarActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        // TODO add your handling code here:
        String queryFacturar = "INSERT INTO "
                + "`factura_cabina` "
                + "(`factura_id`, "
                + "`cant_dia`, "
                + "`fecha`, "
                + "`impuesto_cabina`, "
                + "`precio_total_cabina`, "
                + "`cabina_cabina_id`, "
                + "`colaborador_empleado_id`, "
                + "`numero_factura`, "
                + "`cliente_empresa_empresa_id`) "
                + "VALUES (NULL, '1', '2017-04-17', '1300', '5000', '1', '2', '25', '1')";
        try {
            int P = JOptionPane.showConfirmDialog(null, " Quiere Facturar esta Cabina ?", "Confirmación", JOptionPane.YES_NO_OPTION);
            if (P == 0) {
                con = DBConnection.getConnection();

                if (CantidadDias.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "Favor ingresa el número de días a hospedarse ", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                if (Precio.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "Favor ingresa el monto de la cábina ", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                Statement stmt;
                stmt = con.createStatement();

                pst = con.prepareStatement(queryFacturar);
                pst.execute();
                JOptionPane.showMessageDialog(this, "Guardado con Exito saved", "Gasto Operativo", JOptionPane.INFORMATION_MESSAGE);

                Precio.setText("");
                CantidadDias.setText("");

                Seleccionar_Cabina_frm cabina_frm = new Seleccionar_Cabina_frm();
                this.hide();
                cabina_frm.setVisible(true);

                try {
                    int op = JOptionPane.showConfirmDialog(null, " Cambiar el estado de la cábina # " + nCabina.getText() + " ?", "Confirmación", JOptionPane.YES_NO_OPTION);
                    if (op == 0) {
                        con = DBConnection.getConnection();
                        Statement statement;
                        statement = con.createStatement();

                        String Pru = "UPDATE `cabina` SET `estado_cabina` = 'Ocupado' WHERE `descripcion_cabina` = '" + nCabina.getText() + "' ";
                        pst = con.prepareStatement(Pru);
                        pst.execute();
                        JOptionPane.showMessageDialog(null, "Guardado con Exito saved", "Tipo de Usuario", JOptionPane.INFORMATION_MESSAGE);

                    }

                } catch (HeadlessException | SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }
            }
            if (P == 1) {
                Seleccionar_Cabina_frm cabina_frm = new Seleccionar_Cabina_frm();
                this.hide();
                cabina_frm.setVisible(true);
            }

        } catch (HeadlessException | SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);

        }

    }//GEN-LAST:event_guardarActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        // TODO add your handling code here:
        Seleccionar_Cabina_frm sc = new Seleccionar_Cabina_frm();
        sc.setVisible(true);
        this.hide();
    }//GEN-LAST:event_volverActionPerformed

    private void Precio1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Precio1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_Precio1FocusGained

    private void Precio1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Precio1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_Precio1FocusLost

    private void cmb_clienteEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_clienteEmpresaActionPerformed
        // TODO add your handling code here:
        codigoCliente.setText("");
        try {
            String sqlClienteEmpresa = "SELECT empresa_id, codigo_cliente, nombre FROM pct3.cliente_empresa INNER JOIN pct3.persona ON cliente_empresa.persona_idpersona = persona.idpersona where nombre = '"+ cmb_clienteEmpresa.getSelectedItem() +"'";
            pst = con.prepareStatement(sqlClienteEmpresa);
            rs = pst.executeQuery();
            if (rs.next()) {
                String add1 = rs.getString(1);
                codigoCliente.setText(add1);
                JOptionPane.showMessageDialog(this, rs.getString("empresa_id"));
                String tipoPersonaSeleccionada;
                tipoPersonaSeleccionada = (String) cmb_clienteEmpresa.getSelectedItem();
                nombreCliente1.setText(tipoPersonaSeleccionada);
            }

        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_cmb_clienteEmpresaActionPerformed

    private void cmb_clienteEmpresaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_clienteEmpresaItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmb_clienteEmpresaItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField CantidadDias;
    public static javax.swing.JFormattedTextField Precio;
    public static javax.swing.JFormattedTextField Precio1;
    private javax.swing.JButton borrar;
    private javax.swing.JComboBox<String> cmb_clienteEmpresa;
    private javax.swing.JLabel codigoCliente;
    private javax.swing.JLabel fechaEntrada;
    private javax.swing.JLabel fechaSalida;
    private javax.swing.JButton guardar;
    public static javax.swing.JLabel idCabina;
    private javax.swing.JLabel idCabina1;
    private javax.swing.JLabel idCliente;
    private javax.swing.JLabel idEmpleado;
    public static javax.swing.JLabel idEmpleado1;
    private javax.swing.JTextField impuesto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblCantDias;
    private javax.swing.JLabel lblFacturar;
    private javax.swing.JLabel lblFechaEntrada;
    private javax.swing.JLabel lblImpuesto;
    private javax.swing.JLabel lblRegresar;
    private javax.swing.JLabel lblVaciar;
    public static javax.swing.JLabel nCabina;
    private javax.swing.JLabel nombreCliente;
    private javax.swing.JLabel nombreCliente1;
    public static javax.swing.JLabel nombreEmpleado;
    private javax.swing.JTextField precioTotal;
    private javax.swing.JTextField subTotal;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
