/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.DBConnection;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import static vista.TipoPersona.modeloTipoPersona;

/**
 *
 * @author Eisner López Acevedo <eisner.lopez at gmail.com>
 */
public class frmFactura extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmFactura
     */
    //Conección a la Clase DBConnection que contiene la información de la bd, usuario y contraseña
    private DBConnection myLink = new DBConnection();
    private Connection conexion = DBConnection.getConnection();
    private final String sSQL = "";
    ResultSet rs = null;
    PreparedStatement pst = null;
    public Integer totalregistros;
    //declaración del modelo para Turno u Horario
    static DefaultComboBoxModel modeloCliente = new DefaultComboBoxModel();
    public String var1 = "";

    public frmFactura() {
        initComponents();
    }

    private void ComboCliente() { //para poder llamarlo desde el otro frame o JDialog
        try {
            modeloCliente.removeAllElements(); // eliminamos lo elementos
            Statement stmt;
            stmt = conexion.createStatement();
            String queryComboTipoPersona = "SELECT "
                    + "persona.nombre, "
                    + "cliente_empresa.codigo_cliente, "
                    + "tipo_persona.desc_persona "
                    + "FROM "
                    + "pct3.persona, "
                    + "pct3.cliente_empresa, "
                    + "pct3.tipo_persona"
                    + "WHERE "
                    + "persona.idpersona = cliente_empresa.persona_idpersona"
                    + "AND persona.tipo_persona_idtipo_persona = tipo_persona.idtipo_persona"
                    + "AND tipo_persona.desc_persona = 'cliente';";
            rs = stmt.executeQuery(queryComboTipoPersona);
            while (rs.next()) {
                modeloCliente.addElement(rs.getString("descripcion"));
            }
            txtNombreCliente.setModel(modeloCliente); // seteamos el modelo y se cargan los datos
        } catch (HeadlessException | SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        CantidadDias = new javax.swing.JFormattedTextField();
        lblCantDias = new javax.swing.JLabel();
        fechaEntrada = new javax.swing.JLabel();
        lblFechaEntrada = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fechaSalida = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Precio = new javax.swing.JFormattedTextField();
        borrar = new javax.swing.JButton();
        guardar = new javax.swing.JButton();
        nombreEmpleado = new javax.swing.JLabel();
        nCabina = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblImpuesto = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        impuesto = new javax.swing.JTextField();
        subTotal = new javax.swing.JTextField();
        precioTotal = new javax.swing.JTextField();
        AgregarCliente = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        nombreCliente = new javax.swing.JLabel();
        idCliente = new javax.swing.JLabel();
        idCabina = new javax.swing.JLabel();
        idEmpresa = new javax.swing.JLabel();
        idEmpleado = new javax.swing.JLabel();
        idCliente1 = new javax.swing.JLabel();
        idCabina1 = new javax.swing.JLabel();
        nombreCliente1 = new javax.swing.JLabel();
        idEmpleado1 = new javax.swing.JLabel();
        idEmpresa1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Facturar Cabina");
        setToolTipText("");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Hack", 1, 14)); // NOI18N
        jLabel2.setText("Nombre Cliente");

        CantidadDias.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0"))));
        CantidadDias.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                CantidadDiasFocusLost(evt);
            }
        });
        CantidadDias.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CantidadDiasKeyPressed(evt);
            }
        });

        lblCantDias.setText("Cantidad de Días:");

        fechaEntrada.setFont(new java.awt.Font("Hack", 1, 14)); // NOI18N
        fechaEntrada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fechaEntrada.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblFechaEntrada.setText("Fecha Entrada:");

        jLabel3.setText("Fecha Salida:");

        fechaSalida.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Hack", 1, 14)); // NOI18N
        jLabel1.setText("Precio:");

        Precio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0"))));
        Precio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PrecioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PrecioFocusLost(evt);
            }
        });

        borrar.setBackground(new java.awt.Color(204, 204, 204));
        borrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/compose_64px.png"))); // NOI18N
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });

        guardar.setBackground(new java.awt.Color(204, 204, 204));
        guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/book_64px.png"))); // NOI18N
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        nombreEmpleado.setFont(new java.awt.Font("Hack", 1, 14)); // NOI18N
        nombreEmpleado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreEmpleado.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.darkGray));

        nCabina.setFont(new java.awt.Font("Hack", 1, 14)); // NOI18N
        nCabina.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nCabina.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.lightGray, java.awt.Color.darkGray));

        txtNombreCliente.setFont(new java.awt.Font("Hack", 1, 14)); // NOI18N
        txtNombreCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(CantidadDias, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nCabina, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblFechaEntrada)
                                .addGap(113, 113, 113)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fechaSalida, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(Precio)))
                            .addComponent(lblCantDias)
                            .addComponent(fechaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(borrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(guardar))
                            .addComponent(nombreEmpleado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(28, 28, 28)
                    .addComponent(jLabel2)
                    .addContainerGap(691, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFechaEntrada)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fechaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCantDias)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CantidadDias, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                            .addComponent(Precio))
                        .addGap(6, 6, 6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(guardar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nCabina, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(jLabel2)
                    .addContainerGap(126, Short.MAX_VALUE)))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblImpuesto.setFont(new java.awt.Font("Hack", 1, 14)); // NOI18N
        lblImpuesto.setText("Impuesto:");

        jLabel9.setFont(new java.awt.Font("Hack", 1, 14)); // NOI18N
        jLabel9.setText("Total:");

        jLabel10.setFont(new java.awt.Font("Hack", 1, 14)); // NOI18N
        jLabel10.setText("Sub Total:");

        impuesto.setFont(new java.awt.Font("Hack", 1, 14)); // NOI18N
        impuesto.setEnabled(false);

        subTotal.setFont(new java.awt.Font("Hack", 1, 14)); // NOI18N
        subTotal.setEnabled(false);

        precioTotal.setFont(new java.awt.Font("Hack", 1, 14)); // NOI18N
        precioTotal.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImpuesto)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(impuesto)
                    .addComponent(subTotal)
                    .addComponent(precioTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                .addContainerGap(296, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImpuesto)
                    .addComponent(impuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(31, 31, 31))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(precioTotal)
                        .addContainerGap())))
        );

        AgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarClienteActionPerformed(evt);
            }
        });

        jPanel5.setLayout(new java.awt.GridLayout());

        nombreCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreCliente.setText("nombreCliente");

        idCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        idCliente.setText("idCliente");

        idCabina.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        idCabina.setText("idCabina");

        idEmpresa.setText("idEmpresa");

        idEmpleado.setText("idEmpleado");

        idCliente1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        idCliente1.setText("idCliente");

        idCabina1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        idCabina1.setText("idCabina");

        nombreCliente1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreCliente1.setText("nombreCliente");

        idEmpleado1.setText("idEmpleado");

        idEmpresa1.setText("idEmpresa");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AgregarCliente))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(nombreCliente)
                        .addGap(0, 0, 0)
                        .addComponent(idCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(idCabina, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(idEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(idEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(198, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(nombreCliente1)
                    .addGap(0, 0, 0)
                    .addComponent(idCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(idCabina1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(idEmpresa1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(idEmpleado1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(281, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AgregarCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreCliente)
                    .addComponent(idCliente)
                    .addComponent(idCabina)
                    .addComponent(idEmpresa)
                    .addComponent(idEmpleado))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(219, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nombreCliente1)
                        .addComponent(idCliente1)
                        .addComponent(idCabina1)
                        .addComponent(idEmpresa1)
                        .addComponent(idEmpleado1))
                    .addGap(2, 2, 2)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(254, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CantidadDiasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CantidadDiasFocusLost
        // TODO add your handling code here:
        Calendar c1 = GregorianCalendar.getInstance();
        System.out.println("Fecha actual: " + c1.getTime().toLocaleString());
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
        System.out.println("Fecha Formateada: " + sdf.format(c1.getTime()));
        sdf = new SimpleDateFormat("yyyy/MM/dd");
        System.out.println("Fecha Formateada: " + sdf.format(c1.getTime()));
        int valorDias = Integer.parseInt(CantidadDias.getText());
        if (CantidadDias.getText() == null) {
            JOptionPane.showMessageDialog(null, "Ingrese un valor mayor a 1");
            CantidadDias.requestFocus();
        }
        System.out.println("" + valorDias);
        c1.add(Calendar.DATE, valorDias);
        System.out.println("Fecha Formateada: " + sdf.format(c1.getTime()));
        fechaSalida.setText(sdf.format(c1.getTime()));
    }//GEN-LAST:event_CantidadDiasFocusLost

    private void CantidadDiasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CantidadDiasKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_CantidadDiasKeyPressed

    private void PrecioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PrecioFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecioFocusGained

    private void PrecioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PrecioFocusLost
        // TODO add your handling code here:
        int montoImpuesto, subt, montoTotal;
        montoTotal = Integer.parseInt(Precio.getText()) * Integer.parseInt(CantidadDias.getText());
        montoImpuesto = (int) (montoTotal * 0.13);
        subt = montoTotal - montoImpuesto;
        impuesto.setText(String.valueOf(montoImpuesto));
        precioTotal.setText(String.valueOf(montoTotal));
        subTotal.setText(String.valueOf(subt));
    }//GEN-LAST:event_PrecioFocusLost

    private void AgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarClienteActionPerformed
        // TODO add your handling code here:
        try {
            int P = JOptionPane.showConfirmDialog(null, " Quiere agregar un cliente ?", "Confirmación", JOptionPane.YES_NO_OPTION);
            if (P == 0) {
                conexion = DBConnection.getConnection();

                if (txtNombreCliente.getSelectedItem().toString().equals("")) {
                    JOptionPane.showMessageDialog(this, "Favor ingresa el Nombre y Apellidos ", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                Statement stmt;
                stmt = conexion.createStatement();

                String sql1 = "SELECT * FROM `cliente_empresa` WHERE `nombre_empresa` LIKE '%" + txtNombreCliente.getSelectedItem().toString() + "%'";
                rs = stmt.executeQuery(sql1);
                if (rs.next()) {
                    JOptionPane.showMessageDialog(this, "Valor ya existe.", "Error", JOptionPane.ERROR_MESSAGE);
                    pst = conexion.prepareStatement(sql1);
                    rs = pst.executeQuery();
                    if (rs.next()) {
                        String add1 = rs.getString("empresa_id");
                        String add2 = rs.getString("nombre_empresa");

                        nombreCliente.setText(add2);

                        idCliente.setText(add1);

                    }
                    txtNombreCliente.requestDefaultFocus();
                    return;

                }
                String sqlIns = "INSERT INTO `cliente_empresa`(`nombre_empresa`) VALUES ('" + txtNombreCliente.getSelectedItem().toString()+ "')";
                pst = conexion.prepareStatement(sqlIns);
                pst.execute();
                JOptionPane.showMessageDialog(this, "Guardado con Exito saved", "Gasto Operativo", JOptionPane.INFORMATION_MESSAGE);


            }

        } catch (HeadlessException | SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);

        }
    }//GEN-LAST:event_AgregarClienteActionPerformed

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        // TODO add your handling code here:
        txtNombreCliente.getSelectedItem().toString();
        CantidadDias.setText("");
        impuesto.setText("");
        subTotal.setText("");
        precioTotal.setText("");
    }//GEN-LAST:event_borrarActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        // TODO add your handling code here:
        String queryFacturar = "INSERT INTO `factura_cabina` "
                + "(`factura_id`, `cant_dia`, `fecha`, `impuesto_cabina`, "
                + "`precio_total_cabina`, `cabina_cabina_id`, "
                + "`dato_empresa_iddato_empresa`, "
                + "`cliente_empresa_empresa_id`, "
                + "`colaborador_empleado_id`) VALUES "
                + "(NULL, '" + CantidadDias.getText() + "', "
                + "'" + fechaEntrada.getText() + "', "
                + "'" + impuesto.getText() + "', "
                + "'" + precioTotal.getText() + "', "
                + "'" + idCabina.getText() + "', "
                + "'" + idEmpresa.getText() + "', "
                + "'" + idCliente.getText() + "', "
                + "'" + idEmpleado.getText() + "')";
        try {
            int P = JOptionPane.showConfirmDialog(null, " Quiere Facturar esta Cabina ?", "Confirmación", JOptionPane.YES_NO_OPTION);
            if (P == 0) {
                conexion = DBConnection.getConnection();

                if (txtNombreCliente.getSelectedItem().toString().equals("")) {
                    JOptionPane.showMessageDialog(this, "Favor ingresa el Nombre y Apellidos ", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                if (CantidadDias.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "Favor ingresa el número de días a hospedarse ", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                if (Precio.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "Favor ingresa el monto de la cábina ", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                Statement stmt;
                stmt = conexion.createStatement();

                pst = conexion.prepareStatement(queryFacturar);
                pst.execute();
                JOptionPane.showMessageDialog(this, "Guardado con Exito saved", "Gasto Operativo", JOptionPane.INFORMATION_MESSAGE);
                txtNombreCliente.getSelectedItem();
                Precio.setText("");
                CantidadDias.setText("");

                Seleccionar_Cabina_frm cabina_frm = new Seleccionar_Cabina_frm();
                this.hide();
                cabina_frm.setVisible(true);

                try {
                    int op = JOptionPane.showConfirmDialog(null, " Cambiar el estado de la cábina # " + nCabina.getText() + " ?", "Confirmación", JOptionPane.YES_NO_OPTION);
                    if (op == 0) {
                        conexion = DBConnection.getConnection();
                        Statement statement;
                        statement = conexion.createStatement();

                        String Pru = "UPDATE `cabina` SET `estado_cabina` = 'Ocupado' WHERE `descripcion_cabina` = '" + nCabina.getText() + "' ";
                        pst = conexion.prepareStatement(Pru);
                        pst.execute();
                        JOptionPane.showMessageDialog(null, "Guardado con Exito saved", "Tipo de Usuario", JOptionPane.INFORMATION_MESSAGE);

                    }

                } catch (HeadlessException | SQLException ex) {
                    JOptionPane.showMessageDialog(null, ex);
                }
            }
            if (P == 1) {
                Seleccionar_Cabina_frm cabina_frm = new Seleccionar_Cabina_frm();
                this.hide();
                cabina_frm.setVisible(true);
            }

        } catch (HeadlessException | SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);

        }

    }//GEN-LAST:event_guardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarCliente;
    private javax.swing.JFormattedTextField CantidadDias;
    public static javax.swing.JFormattedTextField Precio;
    private javax.swing.JButton borrar;
    private javax.swing.JLabel fechaEntrada;
    private javax.swing.JLabel fechaSalida;
    private javax.swing.JButton guardar;
    public static javax.swing.JLabel idCabina;
    private javax.swing.JLabel idCabina1;
    private javax.swing.JLabel idCliente;
    private javax.swing.JLabel idCliente1;
    private javax.swing.JLabel idEmpleado;
    private javax.swing.JLabel idEmpleado1;
    private javax.swing.JLabel idEmpresa;
    private javax.swing.JLabel idEmpresa1;
    private javax.swing.JTextField impuesto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblCantDias;
    private javax.swing.JLabel lblFechaEntrada;
    private javax.swing.JLabel lblImpuesto;
    public static javax.swing.JLabel nCabina;
    private javax.swing.JLabel nombreCliente;
    private javax.swing.JLabel nombreCliente1;
    private javax.swing.JLabel nombreEmpleado;
    private javax.swing.JTextField precioTotal;
    private javax.swing.JTextField subTotal;
    private javax.swing.JComboBox<String> txtNombreCliente;
    // End of variables declaration//GEN-END:variables
}
