/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.DBConnection1;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import modelo.contructor.Modelo_Puesto;
import modelo.formularios.Form_Puesto;

/**
 *
 * @author Eisner López Acevedo <eisner.lopez at gmail.com>
 * @author Cesar Gonzalez Salas <cgonzalez816 at gmail.com>
 */
public class TipoPuesto extends javax.swing.JInternalFrame {

    /**
     * Creates new form TipoPersona
     */
    private final DBConnection1 myLink = new DBConnection1();
    private final Connection conexion = DBConnection1.getConnection();
    private final String sSQL = "";
    ResultSet rs = null;
    PreparedStatement pst = null;
    public Integer totalregistros;
    //declaración del modelo para Turno u Horario
    static DefaultComboBoxModel modeloTipoPuesto = new DefaultComboBoxModel();
    public String var1 = "";

    public TipoPuesto() {
        initComponents();
        comboTipoPersona();
    }

    private void comboTipoPersona() { //para poder llamarlo desde el otro frame o JDialog
        try {
            modeloTipoPuesto.removeAllElements(); // eliminamos lo elementos
            Statement stmt;
            stmt = conexion.createStatement();
            String queryComboTipoPersona = "SELECT distinct (descripcion_puesto) as puesto FROM pct3.puesto order by descripcion_puesto;";
            rs = stmt.executeQuery(queryComboTipoPersona);
            while (rs.next()) {
                modeloTipoPuesto.addElement(rs.getString("puesto"));
            }
            comboTipoPersona.setModel(modeloTipoPuesto); // seteamos el modelo y se cargan los datos

        } catch (HeadlessException | SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_MontoHS = new javax.swing.JTextField();
        comboTipoPersona = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txt_MontoHE = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_Puesto = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new java.awt.GridBagLayout());

        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/CRUD/save-icon-silhouette.png"))); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 14, 24, 0);
        jPanel1.add(btnGuardar, gridBagConstraints);

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/CRUD/edit.png"))); // NOI18N
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 12, 24, 0);
        jPanel1.add(btnEditar, gridBagConstraints);

        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/CRUD/dustbin.png"))); // NOI18N
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 12, 24, 25);
        jPanel1.add(btnBorrar, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("HP Simplified Light", 1, 14)); // NOI18N
        jLabel1.setText("Puesto");

        txt_MontoHS.setFont(new java.awt.Font("Hack", 0, 14)); // NOI18N
        txt_MontoHS.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_MontoHSFocusLost(evt);
            }
        });
        txt_MontoHS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_MontoHSKeyPressed(evt);
            }
        });

        comboTipoPersona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboTipoPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTipoPersonaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("HP Simplified Light", 1, 14)); // NOI18N
        jLabel2.setText("Monto Hora Sencilla");

        txt_MontoHE.setFont(new java.awt.Font("Hack", 0, 14)); // NOI18N
        txt_MontoHE.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_MontoHEFocusLost(evt);
            }
        });
        txt_MontoHE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_MontoHEKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("HP Simplified Light", 1, 14)); // NOI18N
        jLabel3.setText("Monto Hora Doble");

        txt_Puesto.setFont(new java.awt.Font("Hack", 0, 14)); // NOI18N
        txt_Puesto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_PuestoFocusLost(evt);
            }
        });
        txt_Puesto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_PuestoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_Puesto, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(comboTipoPersona, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_MontoHS, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_MontoHE, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(comboTipoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_Puesto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_MontoHS, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_MontoHE, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            if (txt_Puesto.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Favor ingresa un tipo de puesto", "Error", JOptionPane.ERROR_MESSAGE);
                txt_Puesto.setText("Aqui");
                return;
            }
            Statement stmt;
            stmt = conexion.createStatement();

            String sql1 = "SELECT `descripcion_puesto` FROM `puesto` WHERE `descripcion_puesto` = '" + txt_Puesto.getText() + "'";
            rs = stmt.executeQuery(sql1);
            if (rs.next()) {
                JOptionPane.showMessageDialog(this, "Tipo Puesto Existente.", "Error", JOptionPane.ERROR_MESSAGE);
                txt_Puesto.setText("");
                return;
            }
        } catch (HeadlessException | SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);

        }

        Modelo_Puesto dts = new Modelo_Puesto();
        Form_Puesto func = new Form_Puesto();
        
        dts.setDescripcion_puesto(txt_Puesto.getText());
        dts.setPago_hora_sencilla(txt_MontoHS.getText());
        dts.setPago_hora_extra(txt_MontoHE.getText());
        if (func.insertar(dts)) {
            JOptionPane.showMessageDialog(rootPane, "el tipo de puesto creado satisfactoriamente");
        }
        txt_MontoHS.setText("");
        comboTipoPersona();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        initComponents();
        if (txt_Puesto.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debes ingresar un tipo persona");
            txt_Puesto.requestFocus();
            return;
        }

        Modelo_Puesto dts = new Modelo_Puesto();
        Form_Puesto func = new Form_Puesto();
        dts.setPuesto_id("null");
        dts.setDescripcion_puesto(txt_Puesto.getText());
        dts.setPago_hora_extra(txt_MontoHS.getText());
        dts.setPago_hora_extra(txt_MontoHE.getText());
        if (func.editar(dts)) {
            JOptionPane.showMessageDialog(rootPane, "Tipo de Puesto editado satisfactoriamente");

        }
        txt_MontoHS.setText("");

        comboTipoPersona();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
        initComponents();
        if (!txt_Puesto.getText().equals("")) {
            int confirmacion = JOptionPane.showConfirmDialog(rootPane, "Estás seguro de Eliminar el dato?", "Confirmar", JOptionPane.YES_NO_OPTION, 2);

            if (confirmacion == 0) {
                Modelo_Puesto dts = new Modelo_Puesto();
                Form_Puesto func = new Form_Puesto();
                dts.setDescripcion_puesto(txt_Puesto.getText());
                func.eliminar(dts);

            }

        }
        txt_Puesto.setText("");
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void txt_PuestoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_PuestoKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingresa Solo Numeros.\n Gracias!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txt_PuestoKeyPressed

    private void txt_PuestoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_PuestoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_PuestoFocusLost

    private void txt_MontoHEKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_MontoHEKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isAlphabetic(c)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingresa Solo Numeros.\n Gracias!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txt_MontoHEKeyPressed

    private void txt_MontoHEFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_MontoHEFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MontoHEFocusLost

    private void comboTipoPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoPersonaActionPerformed
        // TODO add your handling code here:
        
        try {
            String sql = "SELECT puesto_id, descripcion_puesto FROM puesto where descripcion_puesto = '" + comboTipoPersona.getSelectedItem().toString() + "'";
            pst = conexion.prepareStatement(sql);
            rs = pst.executeQuery();
            if (rs.next()) {
                String add1 = rs.getString("puesto_id");
                String add2 = rs.getString("descripcion_puesto");
                var1 = add1;
                txt_Puesto.setText(add2);
            }else
                var1= "";
            txt_Puesto.setText("");

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_comboTipoPersonaActionPerformed

    private void txt_MontoHSKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_MontoHSKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isAlphabetic(c)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingresa Solo Numeros.\n Gracias!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txt_MontoHSKeyPressed

    private void txt_MontoHSFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_MontoHSFocusLost
        // TODO add your handling code here:
        try {
            if (txt_MontoHS.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Favor ingresa un tipo puesto", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            Statement stmt;
            stmt = conexion.createStatement();

            String sql1 = "SELECT `desc_persona` FROM `tipo_persona` WHERE `desc_persona` = '" + txt_MontoHS.getText() + "'";
            rs = stmt.executeQuery(sql1);
            if (rs.next()) {
                JOptionPane.showMessageDialog(this, "Horario existente.", "Error", JOptionPane.ERROR_MESSAGE);
                txt_MontoHS.setText("");
            }
        } catch (HeadlessException | SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);

        }
    }//GEN-LAST:event_txt_MontoHSFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> comboTipoPersona;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_MontoHE;
    private javax.swing.JTextField txt_MontoHS;
    private javax.swing.JTextField txt_Puesto;
    // End of variables declaration//GEN-END:variables
}
